"""Write the updated gaps.html template with expandable action panels."""
import os

path = os.path.join(os.path.dirname(__file__), "templates", "audit", "gaps.html")

# Part 1: Header, styles, summary, filters
lines = []
lines.append('{% extends "base.html" %}')
lines.append('{% block title %}Gap Checklist \u2014 Audit #{{ audit.id }} \u2014 {{ branding.company_name }}{% endblock %}')
lines.append('{% block content %}')
lines.append('<style>')
lines.append('  .gaps-page{max-width:960px;margin:0 auto;padding:1rem;font-family:"Barlow",sans-serif;color:#fff}')
lines.append('  .gaps-page h2{font-family:"Barlow Condensed",sans-serif;color:#f97316;margin-bottom:.5rem;font-size:1.6rem}')
lines.append('  .summary-bar{display:flex;flex-wrap:wrap;gap:.75rem;margin-bottom:1.25rem}')
lines.append('  .summary-card{background:#16213e;border-radius:6px;padding:.6rem 1rem;text-align:center;min-width:100px;flex:1;border:1px solid transparent;transition:all .15s;cursor:pointer;text-decoration:none}')
lines.append('  .summary-card .count{font-family:"Barlow Condensed",sans-serif;font-size:1.5rem;font-weight:700;color:#f97316}')
lines.append('  .summary-card .label{font-size:.8rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em}')
lines.append('  .summary-card:hover{background:#1e293b;border:1px solid #f97316;transform:translateY(-1px)}')
lines.append('  .filter-bar{display:flex;flex-wrap:wrap;gap:.75rem;margin-bottom:1.25rem;align-items:center}')
lines.append('  .filter-bar label{font-size:.85rem;color:#94a3b8}')
lines.append('  .filter-bar select{background:#1e293b;border:1px solid #334155;border-radius:4px;color:#e2e8f0;padding:.4rem .6rem;font-family:"Barlow",sans-serif;font-size:.9rem}')
lines.append('  .filter-bar select:focus{outline:none;border-color:#f97316}')
lines.append('  .filter-bar .filter-btn{background:#f97316;color:#fff;border:none;border-radius:4px;padding:.4rem 1rem;cursor:pointer;font-weight:600}')
lines.append('  .filter-bar .filter-btn:hover{background:#fb923c}')
lines.append('  .filter-bar .clear-btn{background:transparent;color:#94a3b8;border:1px solid #334155;border-radius:4px;padding:.4rem .75rem;cursor:pointer;text-decoration:none;font-size:.9rem}')
lines.append('  .filter-bar .clear-btn:hover{color:#fff;border-color:#f97316}')
lines.append('  .gap-card{background:#0f172a;border:1px solid #334155;border-radius:6px;padding:1rem;margin-bottom:1rem}')
lines.append('  .gap-header{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap;margin-bottom:.75rem}')
lines.append('  .gap-code{font-family:"Barlow Condensed",sans-serif;font-weight:700;font-size:1.1rem;color:#e2e8f0}')
lines.append('  .gap-title{color:#cbd5e1;font-size:.95rem}')
lines.append('  .gap-score{font-family:"Barlow Condensed",sans-serif;font-weight:700;font-size:.95rem;padding:.15rem .5rem;border-radius:4px;background:#1e293b;color:#94a3b8}')
lines.append('  .badge{display:inline-block;padding:.15rem .5rem;border-radius:4px;font-size:.8rem;font-weight:600;text-transform:uppercase;letter-spacing:.03em}')
lines.append('  .badge-critical{background:rgba(239,68,68,.2);color:#f87171;border:1px solid rgba(239,68,68,.3)}')
lines.append('  .badge-high{background:rgba(249,115,22,.2);color:#fb923c;border:1px solid rgba(249,115,22,.3)}')
lines.append('  .badge-medium{background:rgba(250,204,21,.2);color:#fbbf24;border:1px solid rgba(250,204,21,.3)}')
lines.append('  .actions-section{margin-top:.5rem}')
lines.append('  .actions-section h4{font-family:"Barlow Condensed",sans-serif;color:#94a3b8;font-size:.9rem;margin:0 0 .4rem;text-transform:uppercase;letter-spacing:.05em}')
lines.append('  .action-item{background:#16213e;border-radius:4px;margin-bottom:.4rem;border:1px solid #1e293b;overflow:hidden}')
lines.append('  .action-summary{display:flex;flex-wrap:wrap;align-items:center;gap:.5rem;padding:.5rem .75rem;cursor:pointer;user-select:none}')
lines.append('  .action-summary:hover{background:#1e293b}')
lines.append('  .action-expand-icon{color:#64748b;font-size:.75rem;transition:transform .2s;min-width:16px}')
lines.append('  .action-item.expanded .action-expand-icon{transform:rotate(90deg)}')
lines.append('  .action-desc{flex:1;color:#e2e8f0;font-size:.9rem;min-width:150px}')
lines.append('  .action-meta{color:#94a3b8;font-size:.8rem}')
lines.append('  .action-status{padding:.1rem .4rem;border-radius:3px;font-size:.8rem;font-weight:600}')
lines.append('  .status-open{background:rgba(59,130,246,.2);color:#60a5fa}')
lines.append('  .status-in_progress{background:rgba(250,204,21,.2);color:#fbbf24}')
lines.append('  .status-completed{background:rgba(74,222,128,.2);color:#4ade80}')
lines.append('  .status-overdue{background:rgba(239,68,68,.2);color:#f87171}')
lines.append('  .action-detail{display:none;padding:.75rem;border-top:1px solid #334155;background:#0f172a}')
lines.append('  .action-item.expanded .action-detail{display:block}')
lines.append('  .detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:.75rem}')
lines.append('  .detail-field label{display:block;font-size:.8rem;color:#94a3b8;margin-bottom:.2rem}')
lines.append('  .detail-field select,.detail-field input{background:#1e293b;border:1px solid #334155;border-radius:4px;color:#e2e8f0;padding:.35rem .5rem;font-size:.85rem;width:100%}')
lines.append('  .detail-field select:focus,.detail-field input:focus,.detail-field textarea:focus{outline:none;border-color:#f97316}')
lines.append('  .detail-field textarea{background:#1e293b;border:1px solid #334155;border-radius:4px;color:#e2e8f0;padding:.35rem .5rem;font-size:.85rem;width:100%;min-height:50px;resize:vertical}')
lines.append('  .detail-full{grid-column:1/-1}')
lines.append('  .detail-actions{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.5rem}')
lines.append('  .btn-save{background:#f97316;color:#fff;border:none;border-radius:4px;padding:.35rem .75rem;cursor:pointer;font-weight:600;font-size:.85rem}')
lines.append('  .btn-save:hover{background:#fb923c}')
lines.append('  .btn-complete{background:#22c55e;color:#fff;border:none;border-radius:4px;padding:.35rem .75rem;cursor:pointer;font-weight:600;font-size:.85rem}')
lines.append('  .btn-complete:hover{background:#16a34a}')
lines.append('  .btn-reopen{background:#3b82f6;color:#fff;border:none;border-radius:4px;padding:.35rem .75rem;cursor:pointer;font-weight:600;font-size:.85rem}')
lines.append('  .btn-reopen:hover{background:#2563eb}')
lines.append('  .completed-banner{background:rgba(74,222,128,.1);border:1px solid rgba(74,222,128,.3);border-radius:4px;padding:.5rem .75rem;margin-bottom:.5rem;font-size:.85rem;color:#4ade80}')
lines.append('  .evidence-section{margin-top:.75rem;border-top:1px solid #334155;padding-top:.5rem}')
lines.append('  .evidence-section h5{font-family:"Barlow Condensed",sans-serif;color:#94a3b8;font-size:.85rem;margin:0 0 .4rem;text-transform:uppercase}')
lines.append('  .evidence-file{display:flex;align-items:center;gap:.5rem;padding:.3rem .5rem;background:#1e293b;border-radius:3px;margin-bottom:.25rem;font-size:.85rem}')
lines.append('  .evidence-file .ev-name{flex:1;color:#e2e8f0}')
lines.append('  .evidence-file .ev-size{color:#64748b;font-size:.75rem}')
lines.append('  .evidence-file .ev-delete{background:transparent;border:none;color:#f87171;cursor:pointer;font-size:.85rem;padding:.1rem .3rem}')
lines.append('  .evidence-file .ev-delete:hover{color:#ef4444}')
lines.append('  .evidence-upload{margin-top:.4rem}')
lines.append('  .evidence-upload input[type="file"]{font-size:.8rem;color:#94a3b8}')
lines.append('  .add-action-toggle{background:transparent;color:#f97316;border:1px dashed #f97316;border-radius:4px;padding:.35rem .75rem;cursor:pointer;font-size:.85rem;margin-top:.5rem}')
lines.append('  .add-action-toggle:hover{background:rgba(249,115,22,.1)}')
lines.append('  .add-action-form{background:#16213e;border:1px solid #334155;border-radius:6px;padding:.75rem;margin-top:.5rem;display:none}')
lines.append('  .add-action-form.visible{display:block}')
lines.append('  .add-action-form .form-row{display:flex;flex-wrap:wrap;gap:.5rem;margin-bottom:.5rem}')
lines.append('  .add-action-form label{display:block;font-size:.8rem;color:#94a3b8;margin-bottom:.2rem}')
lines.append('  .add-action-form input,.add-action-form textarea,.add-action-form select{background:#1e293b;border:1px solid #334155;border-radius:4px;color:#e2e8f0;padding:.4rem .5rem;font-size:.9rem;width:100%}')
lines.append('  .add-action-form textarea{min-height:60px;resize:vertical}')
lines.append('  .add-action-form .field{flex:1;min-width:140px}')
lines.append('  .back-link{display:inline-flex;align-items:center;gap:.4rem;padding:.5rem 1rem;background:#1e293b;border:1px solid #334155;border-radius:6px;color:#f97316;text-decoration:none;font-weight:600;transition:all .15s;margin-bottom:1rem}')
lines.append('  .back-link:hover{background:#f97316;color:#fff;border-color:#f97316}')
lines.append('  .empty-state{text-align:center;padding:2rem;color:#94a3b8}')
lines.append('  .read-only-val{color:#e2e8f0;font-size:.85rem;padding:.35rem 0}')
lines.append('</style>')
lines.append('')

# HTML body
lines.append('<div class="gaps-page">')
lines.append('  <a href="{{ url_for(\'audits.audit_detail\', audit_id=audit.id) }}" class="back-link">&#8592; Back to Audit</a>')
lines.append('  <h2>Gap Checklist \u2014 Audit #{{ audit.id }}</h2>')
lines.append('')
lines.append('  <div class="summary-bar">')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id) }}" class="summary-card"><div class="count">{{ summary.total }}</div><div class="label">Total</div></a>')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id, priority=\'critical\') }}" class="summary-card"><div class="count" style="color:#f87171;">{{ summary.critical }}</div><div class="label">Critical</div></a>')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id, priority=\'high\') }}" class="summary-card"><div class="count" style="color:#fb923c;">{{ summary.high }}</div><div class="label">High</div></a>')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id, priority=\'medium\') }}" class="summary-card"><div class="count" style="color:#fbbf24;">{{ summary.medium }}</div><div class="label">Medium</div></a>')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id, status=\'Open\') }}" class="summary-card"><div class="count" style="color:#60a5fa;">{{ summary.actions_open }}</div><div class="label">Actions Open</div></a>')
lines.append('    <a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id, status=\'Completed\') }}" class="summary-card"><div class="count" style="color:#4ade80;">{{ summary.actions_closed }}</div><div class="label">Actions Closed</div></a>')
lines.append('  </div>')
lines.append('')
lines.append('  <form class="filter-bar" method="get" action="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id) }}">')
lines.append('    <div><label for="pf">Priority:</label>')
lines.append('      <select name="priority" id="pf">')
lines.append('        <option value="">All</option>')
lines.append("        <option value=\"critical\" {% if priority_filter == 'critical' %}selected{% endif %}>Critical</option>")
lines.append("        <option value=\"high\" {% if priority_filter == 'high' %}selected{% endif %}>High</option>")
lines.append("        <option value=\"medium\" {% if priority_filter == 'medium' %}selected{% endif %}>Medium</option>")
lines.append('      </select></div>')
lines.append('    <div><label for="sf">Status:</label>')
lines.append('      <select name="status" id="sf">')
lines.append('        <option value="">All</option>')
lines.append("        <option value=\"Open\" {% if status_filter == 'Open' %}selected{% endif %}>Open</option>")
lines.append("        <option value=\"In_Progress\" {% if status_filter == 'In_Progress' %}selected{% endif %}>In Progress</option>")
lines.append("        <option value=\"Completed\" {% if status_filter == 'Completed' %}selected{% endif %}>Completed</option>")
lines.append("        <option value=\"Overdue\" {% if status_filter == 'Overdue' %}selected{% endif %}>Overdue</option>")
lines.append('      </select></div>')
lines.append('    <button type="submit" class="filter-btn">Filter</button>')
lines.append('    {% if priority_filter or status_filter %}<a href="{{ url_for(\'audits.audit_gaps\', audit_id=audit.id) }}" class="clear-btn">Clear</a>{% endif %}')
lines.append('  </form>')
lines.append('')
lines.append("  {% set is_locked = audit.status in ('Completed', 'Archived') %}")

# Gap items loop
lines.append('  {% if gap_items %}')
lines.append('    {% for gap in gap_items %}')
lines.append('    <div class="gap-card" data-criterion-code="{{ gap.code }}">')
lines.append('      <div class="gap-header">')
lines.append('        <span class="gap-code">{{ gap.code }}</span>')
lines.append('        <span class="gap-title">{{ gap.title }}</span>')
lines.append('        <span class="gap-score">Score: {{ gap.score }}</span>')
lines.append("        {% if gap.priority == 'critical' %}<span class=\"badge badge-critical\">Critical</span>")
lines.append("        {% elif gap.priority == 'high' %}<span class=\"badge badge-high\">High</span>")
lines.append('        {% else %}<span class="badge badge-medium">Medium</span>{% endif %}')
lines.append('      </div>')
lines.append('      <div class="actions-section">')
lines.append('        {% if gap.actions %}')
lines.append('        <h4>Corrective Actions ({{ gap.actions|length }})</h4>')
lines.append('        {% for action in gap.actions %}')
lines.append('        <div class="action-item" id="action-{{ action.id }}">')
lines.append('          <div class="action-summary" onclick="toggleAction({{ action.id }})">')
lines.append('            <span class="action-expand-icon">&#9654;</span>')
lines.append("            <span class=\"action-desc\">{{ action.description[:120] }}{% if action.description|length > 120 %}\u2026{% endif %}</span>")
lines.append("            {% if action.due_date %}<span class=\"action-meta\">Due: {{ action.due_date.strftime('%Y-%m-%d') }}</span>{% endif %}")
lines.append('            {% if action.assigned_to %}<span class="action-meta">{{ action.assigned_to.display_name }}</span>{% endif %}')
lines.append('            <span class="action-status status-{{ action.status|lower }}">{{ action.status|replace(\'_\', \' \') }}</span>')
lines.append('          </div>')

# Action detail panel
lines.append('          <div class="action-detail">')
lines.append("            {% if action.status == 'Completed' and action.completed_at %}")
lines.append('            <div class="completed-banner">')
lines.append("              Completed {{ action.completed_at.strftime('%Y-%m-%d %H:%M') }}{% if action.completed_by %} by {{ action.completed_by.display_name }}{% endif %}")
lines.append('            </div>')
lines.append('            {% endif %}')
lines.append('            <div class="detail-grid">')

# Status field
lines.append('              <div class="detail-field"><label>Status</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.status|replace('_', ' ') }}</div>")
lines.append('                {% else %}<select id="status-{{ action.id }}">')
lines.append("                  <option value=\"Open\" {% if action.status == 'Open' %}selected{% endif %}>Open</option>")
lines.append("                  <option value=\"In_Progress\" {% if action.status == 'In_Progress' %}selected{% endif %}>In Progress</option>")
lines.append("                  <option value=\"Completed\" {% if action.status == 'Completed' %}selected{% endif %}>Completed</option>")
lines.append("                  <option value=\"Overdue\" {% if action.status == 'Overdue' %}selected{% endif %}>Overdue</option>")
lines.append('                </select>{% endif %}</div>')

# Priority field
lines.append('              <div class="detail-field"><label>Priority</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.priority|capitalize }}</div>")
lines.append('                {% else %}<select id="priority-{{ action.id }}">')
lines.append("                  <option value=\"critical\" {% if action.priority == 'critical' %}selected{% endif %}>Critical</option>")
lines.append("                  <option value=\"high\" {% if action.priority == 'high' %}selected{% endif %}>High</option>")
lines.append("                  <option value=\"medium\" {% if action.priority == 'medium' %}selected{% endif %}>Medium</option>")
lines.append('                </select>{% endif %}</div>')

# Assigned To field
lines.append('              <div class="detail-field"><label>Assigned To</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.assigned_to.display_name if action.assigned_to else '\u2014' }}</div>")
lines.append('                {% else %}<select id="assigned-{{ action.id }}">')
lines.append('                  <option value="">Unassigned</option>')
lines.append('                  {% for u in users %}<option value="{{ u.id }}" {% if action.assigned_to_id == u.id %}selected{% endif %}>{{ u.display_name }}</option>{% endfor %}')
lines.append('                </select>{% endif %}</div>')

# Due Date field
lines.append('              <div class="detail-field"><label>Due Date</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.due_date.strftime('%Y-%m-%d') if action.due_date else '\u2014' }}</div>")
lines.append("                {% else %}<input type=\"date\" id=\"due-{{ action.id }}\" value=\"{{ action.due_date.strftime('%Y-%m-%d') if action.due_date else '' }}\">{% endif %}</div>")

# Description (full width)
lines.append('              <div class="detail-field detail-full"><label>Description</label>')
lines.append('                {% if is_locked %}<div class="read-only-val">{{ action.description }}</div>')
lines.append('                {% else %}<textarea id="desc-{{ action.id }}" rows="2">{{ action.description }}</textarea>{% endif %}</div>')

# Notes
lines.append('              <div class="detail-field detail-full"><label>Notes</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.notes or '\u2014' }}</div>")
lines.append('                {% else %}<textarea id="notes-{{ action.id }}" rows="2" placeholder="Working notes\u2026">{{ action.notes or \'\' }}</textarea>{% endif %}</div>')

# Resolution Notes
lines.append('              <div class="detail-field detail-full"><label>Resolution Notes</label>')
lines.append("                {% if is_locked %}<div class=\"read-only-val\">{{ action.resolution_notes or '\u2014' }}</div>")
lines.append('                {% else %}<textarea id="resnotes-{{ action.id }}" rows="2" placeholder="How was this resolved?">{{ action.resolution_notes or \'\' }}</textarea>{% endif %}</div>')

lines.append('            </div>')

# Action buttons
lines.append('            {% if not is_locked %}')
lines.append('            <div class="detail-actions">')
lines.append('              <button class="btn-save" onclick="saveAction({{ audit.id }}, {{ action.id }})">Save Changes</button>')
lines.append("              {% if action.status != 'Completed' %}")
lines.append('              <button class="btn-complete" onclick="completeAction({{ audit.id }}, {{ action.id }})">Mark Complete</button>')
lines.append('              {% else %}')
lines.append('              <button class="btn-reopen" onclick="reopenAction({{ audit.id }}, {{ action.id }})">Reopen</button>')
lines.append('              {% endif %}')
lines.append('            </div>')
lines.append('            {% endif %}')

# Evidence section
lines.append('            <div class="evidence-section">')
lines.append('              <h5>Evidence Files</h5>')
lines.append('              <div id="evidence-list-{{ action.id }}">')
lines.append('                {% for ev in action.evidence_files %}')
lines.append('                <div class="evidence-file" id="ev-{{ ev.id }}">')
lines.append('                  <span class="ev-name">{{ ev.original_filename }}</span>')
lines.append('                  <span class="ev-size">{{ (ev.file_size / 1024)|round(1) }} KB</span>')
lines.append('                  {% if not is_locked %}<button class="ev-delete" onclick="deleteEvidence({{ ev.id }})" title="Delete">&#10005;</button>{% endif %}')
lines.append('                </div>')
lines.append('                {% endfor %}')
lines.append('              </div>')
lines.append('              {% if not is_locked %}')
lines.append('              <div class="evidence-upload">')
lines.append('                <input type="file" id="evfile-{{ action.id }}" onchange="uploadEvidence({{ audit.id }}, {{ action.id }}, this)">')
lines.append('              </div>')
lines.append('              {% endif %}')
lines.append('            </div>')

lines.append('          </div>') # close action-detail
lines.append('        </div>') # close action-item
lines.append('        {% endfor %}')
lines.append('        {% else %}')
lines.append('        <p style="color:#64748b;font-size:.85rem;margin:.25rem 0;">No corrective actions yet.</p>')
lines.append('        {% endif %}')

# Add action button and form
lines.append('        {% if not is_locked %}')
lines.append('        <button class="add-action-toggle" onclick="toggleAddForm(this)">+ Add Action</button>')
lines.append('        <div class="add-action-form" data-audit-id="{{ audit.id }}" data-code="{{ gap.code }}">')
lines.append('          <div class="form-row">')
lines.append('            <div class="field" style="flex:2;"><label>Description</label><textarea name="description" placeholder="Describe the corrective action\u2026"></textarea></div>')
lines.append('          </div>')
lines.append('          <div class="form-row">')
lines.append('            <div class="field"><label>Priority</label>')
lines.append('              <select name="priority">')
lines.append("                <option value=\"critical\" {% if gap.priority == 'critical' %}selected{% endif %}>Critical</option>")
lines.append("                <option value=\"high\" {% if gap.priority == 'high' %}selected{% endif %}>High</option>")
lines.append('                <option value="medium">Medium</option>')
lines.append('              </select></div>')
lines.append('            <div class="field"><label>Due Date</label><input type="date" name="due_date"></div>')
lines.append('            <div class="field"><label>Assign To</label>')
lines.append('              <select name="assigned_to_id">')
lines.append('                <option value="">Unassigned</option>')
lines.append('                {% for u in users %}<option value="{{ u.id }}">{{ u.display_name }}</option>{% endfor %}')
lines.append('              </select></div>')
lines.append('          </div>')
lines.append('          <button type="button" class="btn-save" onclick="submitAction(this)">Create Action</button>')
lines.append('        </div>')
lines.append('        {% endif %}')
lines.append('      </div>') # close actions-section
lines.append('    </div>') # close gap-card
lines.append('    {% endfor %}')
lines.append('  {% else %}')
lines.append('    <div class="empty-state"><p>No gaps found{% if priority_filter or status_filter %} matching the current filters{% endif %}.</p></div>')
lines.append('  {% endif %}')
lines.append('</div>')

# JavaScript
lines.append('')
lines.append('<script>')
lines.append('function toggleAction(actionId) {')
lines.append("  var el = document.getElementById('action-' + actionId);")
lines.append("  if (el) el.classList.toggle('expanded');")
lines.append('}')
lines.append('')
lines.append('function toggleAddForm(btn) {')
lines.append('  var form = btn.nextElementSibling;')
lines.append("  form.classList.toggle('visible');")
lines.append('}')
lines.append('')
lines.append('function submitAction(btn) {')
lines.append("  var form = btn.closest('.add-action-form');")
lines.append('  var auditId = form.dataset.auditId;')
lines.append('  var code = form.dataset.code;')
lines.append("  var desc = form.querySelector('textarea[name=\"description\"]').value.trim();")
lines.append("  var priority = form.querySelector('select[name=\"priority\"]').value;")
lines.append("  var dueDate = form.querySelector('input[name=\"due_date\"]').value;")
lines.append("  var assignedTo = form.querySelector('select[name=\"assigned_to_id\"]').value;")
lines.append("  if (!desc) { alert('Please enter a description.'); return; }")
lines.append('  var body = { criterion_code: code, description: desc, priority: priority };')
lines.append('  if (dueDate) body.due_date = dueDate;')
lines.append('  if (assignedTo) body.assigned_to_id = parseInt(assignedTo);')
lines.append("  fetch('/api/audits/' + auditId + '/actions', {")
lines.append("    method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body)")
lines.append('  }).then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) location.reload(); else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('')
lines.append('function saveAction(auditId, actionId) {')
lines.append('  var body = {')
lines.append("    status: document.getElementById('status-' + actionId).value,")
lines.append("    priority: document.getElementById('priority-' + actionId).value,")
lines.append("    assigned_to_id: document.getElementById('assigned-' + actionId).value || null,")
lines.append("    due_date: document.getElementById('due-' + actionId).value || null,")
lines.append("    description: document.getElementById('desc-' + actionId).value.trim(),")
lines.append("    notes: document.getElementById('notes-' + actionId).value.trim() || null,")
lines.append("    resolution_notes: document.getElementById('resnotes-' + actionId).value.trim() || null")
lines.append('  };')
lines.append("  fetch('/api/audits/' + auditId + '/actions/' + actionId, {")
lines.append("    method: 'PUT', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body)")
lines.append('  }).then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) location.reload(); else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('')
lines.append('function completeAction(auditId, actionId) {')
lines.append("  var notes = document.getElementById('notes-' + actionId).value.trim();")
lines.append("  var resNotes = document.getElementById('resnotes-' + actionId).value.trim();")
lines.append("  var body = { status: 'Completed', notes: notes || null, resolution_notes: resNotes || null };")
lines.append("  fetch('/api/audits/' + auditId + '/actions/' + actionId, {")
lines.append("    method: 'PUT', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body)")
lines.append('  }).then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) location.reload(); else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('')
lines.append('function reopenAction(auditId, actionId) {')
lines.append("  fetch('/api/audits/' + auditId + '/actions/' + actionId, {")
lines.append("    method: 'PUT', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ status: 'Open' })")
lines.append('  }).then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) location.reload(); else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('')
lines.append('function uploadEvidence(auditId, actionId, input) {')
lines.append('  if (!input.files || !input.files[0]) return;')
lines.append('  var fd = new FormData();')
lines.append("  fd.append('file', input.files[0]);")
lines.append("  fetch('/api/audits/' + auditId + '/actions/' + actionId + '/evidence', {")
lines.append("    method: 'POST', body: fd")
lines.append('  }).then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) location.reload(); else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('')
lines.append('function deleteEvidence(evidenceId) {')
lines.append("  if (!confirm('Delete this evidence file?')) return;")
lines.append("  fetch('/api/action-evidence/' + evidenceId, { method: 'DELETE' })")
lines.append('  .then(function(r) { return r.json(); }).then(function(d) {')
lines.append("    if (d.ok) { var el = document.getElementById('ev-' + evidenceId); if (el) el.remove(); }")
lines.append("    else alert('Error: ' + (d.error || 'Unknown'));")
lines.append("  }).catch(function(e) { alert('Network error: ' + e.message); });")
lines.append('}')
lines.append('</script>')
lines.append('{% endblock %}')

content = "\n".join(lines)
with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Written {len(content)} chars, {len(lines)} lines to {path}")
