"""ISO 14001:2015 - Environmental Management System template seed data."""

TEMPLATE_NAME = "ISO 14001:2015 \u2014 Environmental Management System"
TEMPLATE_VERSION = "1.0"
TEMPLATE_METADATA = {"domain_type": "Management Systems", "compliance_framework": "ISO 14001:2015"}

SECTIONS = [
    {"name": "Clause 4: Context of the Organisation", "codes": ["EMS-4.1", "EMS-4.2", "EMS-4.3"]},
    {"name": "Clause 5: Leadership", "codes": ["EMS-5.1", "EMS-5.2", "EMS-5.3"]},
    {"name": "Clause 6: Planning", "codes": ["EMS-6.1", "EMS-6.2", "EMS-6.3"]},
    {"name": "Clause 7: Support", "codes": ["EMS-7.1", "EMS-7.2", "EMS-7.3"]},
    {"name": "Clause 8: Operation", "codes": ["EMS-8.1", "EMS-8.2", "EMS-8.3"]},
    {"name": "Clause 9: Performance Evaluation", "codes": ["EMS-9.1", "EMS-9.2", "EMS-9.3"]},
    {"name": "Clause 10: Improvement", "codes": ["EMS-10.1", "EMS-10.2", "EMS-10.3"]},
]

def _s(scores):
    return [{"score": i, "description": d} for i, d in enumerate(scores)]

def _e(items):
    return [{"text": t, "age_label": "< 12 months", "age_class": "age-1y", "required": r} for t, r in items]

CRITERIA = {
    "EMS-4.1": {
        "title": "Understanding the Organisation and Its Context",
        "guidance": "Determine external and internal issues relevant to the EMS.",
        "question": "Has the organisation identified issues relevant to its purpose and the EMS?",
        "na_allowed": False,
        "scoring": _s(["No identification of environmental context issues.",
                        "Some issues informally recognised but not documented.",
                        "Issues documented but not linked to EMS planning.",
                        "Issues identified including environmental conditions and used as EMS input.",
                        "Comprehensive scanning with lifecycle perspective integrated into planning."]),
        "evidence": _e([("Environmental context analysis document", True),
                         ("Management review minutes referencing environmental context", True)]),
    },
    "EMS-4.2": {
        "title": "Needs and Expectations of Interested Parties",
        "guidance": "Determine interested parties, their needs, and compliance obligations.",
        "question": "Has the organisation identified interested parties and compliance obligations?",
        "na_allowed": False,
        "scoring": _s(["No identification of interested parties.",
                        "Regulators identified but other stakeholders not considered.",
                        "Parties listed but compliance obligations not derived.",
                        "All parties identified with documented compliance obligations.",
                        "Stakeholder engagement programme with proactive consultation."]),
        "evidence": _e([("Interested parties register", True), ("Compliance obligations register", True)]),
    },
    "EMS-4.3": {
        "title": "Determining the Scope of the EMS",
        "guidance": "Determine boundaries and applicability of the EMS.",
        "question": "Is the scope of the EMS clearly defined and documented?",
        "na_allowed": False,
        "scoring": _s(["No defined EMS scope.", "Scope exists informally.", "Scope documented but lifecycle not applied.",
                        "Scope clearly defined with lifecycle perspective.", "Scope reviewed with lifecycle assessment."]),
        "evidence": _e([("EMS scope statement", True), ("Environmental manual referencing scope", True)]),
    },
    "EMS-5.1": {
        "title": "Leadership and Commitment",
        "guidance": "Top management shall demonstrate leadership and commitment to the EMS.",
        "question": "Does top management demonstrate leadership and commitment to the EMS?",
        "na_allowed": False,
        "scoring": _s(["No visible management commitment.", "Management aware but not actively involved.",
                        "Management participates in reviews but does not drive culture.",
                        "Top management actively leads EMS and promotes pollution prevention.",
                        "Environmental leadership embedded in governance with sustainability KPIs."]),
        "evidence": _e([("Management review minutes showing environmental leadership", True),
                         ("Evidence of resource allocation for EMS", True)]),
    },
    "EMS-5.2": {
        "title": "Environmental Policy",
        "guidance": "Establish an environmental policy with commitments to protection, prevention, compliance, and improvement.",
        "question": "Is an environmental policy established with required commitments?",
        "na_allowed": False,
        "scoring": _s(["No environmental policy.", "Policy exists but outdated.", "Policy documented but not communicated.",
                        "Policy appropriate, communicated, and available to interested parties.",
                        "Policy integrated into corporate values and sustainability strategy."]),
        "evidence": _e([("Environmental policy signed by top management", True),
                         ("Evidence of policy communication", True)]),
    },
    "EMS-5.3": {
        "title": "Organisational Roles, Responsibilities and Authorities",
        "guidance": "Ensure EMS roles are assigned, communicated, and understood.",
        "question": "Are EMS roles and responsibilities clearly assigned and communicated?",
        "na_allowed": False,
        "scoring": _s(["No defined EMS roles.", "Some roles informally assigned.", "Roles documented but not communicated.",
                        "All roles defined, assigned, and communicated.",
                        "RACI matrix with competency mapping and environmental champions."]),
        "evidence": _e([("EMS roles and responsibilities matrix", True),
                         ("Job descriptions referencing environmental responsibilities", False)]),
    },
    "EMS-6.1": {
        "title": "Environmental Aspects",
        "guidance": "Determine environmental aspects and significant impacts using a lifecycle perspective.",
        "question": "Has the organisation identified environmental aspects and significant impacts?",
        "na_allowed": False,
        "scoring": _s(["No identification of environmental aspects.", "Some aspects informally recognised.",
                        "Aspects register exists but lifecycle not applied.",
                        "Aspects systematically identified with lifecycle perspective.",
                        "Comprehensive lifecycle assessment with quantified impacts."]),
        "evidence": _e([("Environmental aspects and impacts register", True),
                         ("Significance evaluation criteria", True)]),
    },
    "EMS-6.2": {
        "title": "Compliance Obligations",
        "guidance": "Determine and have access to compliance obligations related to environmental aspects.",
        "question": "Has the organisation identified all applicable environmental compliance obligations?",
        "na_allowed": False,
        "scoring": _s(["No identification of compliance obligations.", "Key legislation known but no register.",
                        "Legal register exists but not regularly updated.",
                        "All obligations identified, access maintained, and integrated into EMS.",
                        "Automated legal tracking with change alerts and compliance mapping."]),
        "evidence": _e([("Legal and other requirements register", True),
                         ("Evidence of compliance obligation review process", True)]),
    },
    "EMS-6.3": {
        "title": "Environmental Objectives and Planning",
        "guidance": "Establish environmental objectives at relevant functions and levels.",
        "question": "Are measurable environmental objectives established and monitored?",
        "na_allowed": False,
        "scoring": _s(["No environmental objectives.", "Objectives exist but vague.",
                        "Measurable objectives set but not consistently monitored.",
                        "SMART objectives linked to significant aspects with achievement plans.",
                        "Science-based targets with real-time dashboards and trend analysis."]),
        "evidence": _e([("Environmental objectives with targets and timelines", True),
                         ("Objective monitoring and performance reports", True)]),
    },
    "EMS-7.1": {
        "title": "Competence and Awareness",
        "guidance": "Determine competence of persons affecting environmental performance.",
        "question": "Are personnel competent and aware of significant aspects?",
        "na_allowed": False,
        "scoring": _s(["No environmental competence requirements.", "Basic induction only.",
                        "Training provided but not linked to significant aspects.",
                        "Competence requirements defined with awareness programme.",
                        "Competency framework with skills matrix and effectiveness evaluation."]),
        "evidence": _e([("Environmental training records", True), ("Awareness programme materials", True)]),
    },
    "EMS-7.2": {
        "title": "Communication",
        "guidance": "Establish processes for internal and external environmental communications.",
        "question": "Are environmental communication processes established?",
        "na_allowed": False,
        "scoring": _s(["No environmental communication processes.", "Ad-hoc communication only.",
                        "Some processes but external communication not addressed.",
                        "Internal and external processes defined covering what, when, with whom, and how.",
                        "Integrated stakeholder communication strategy with sustainability reporting."]),
        "evidence": _e([("Environmental communication procedure", True),
                         ("Records of environmental communications", False)]),
    },
    "EMS-7.3": {
        "title": "Documented Information",
        "guidance": "Control EMS documented information for availability and protection.",
        "question": "Is EMS documented information controlled and protected?",
        "na_allowed": False,
        "scoring": _s(["No document control.", "Some documents controlled but many informal.",
                        "Document control exists but version management inconsistent.",
                        "Documented information controlled with version management and retention.",
                        "Electronic document management with automated workflows."]),
        "evidence": _e([("Document control procedure for EMS", True),
                         ("Master document list for environmental records", True)]),
    },
    "EMS-8.1": {
        "title": "Operational Planning and Control",
        "guidance": "Establish controls for significant environmental aspects using lifecycle perspective.",
        "question": "Are operational controls established for significant aspects?",
        "na_allowed": False,
        "scoring": _s(["No operational controls.", "Some controls but not linked to significant aspects.",
                        "Controls in place but lifecycle perspective not applied.",
                        "Controls established for all significant aspects with lifecycle perspective.",
                        "Integrated control system with real-time monitoring."]),
        "evidence": _e([("Operational control procedures", True),
                         ("Environmental requirements for procurement", True)]),
    },
    "EMS-8.2": {
        "title": "Emergency Preparedness and Response",
        "guidance": "Establish processes to prepare for and respond to environmental emergencies.",
        "question": "Are emergency procedures established for environmental emergencies?",
        "na_allowed": False,
        "scoring": _s(["No environmental emergency preparedness.", "Basic contacts but no procedures.",
                        "Procedures exist but not tested.",
                        "Procedures established for all potential emergencies and periodically tested.",
                        "Comprehensive emergency management with spill containment."]),
        "evidence": _e([("Environmental emergency response plan", True),
                         ("Emergency drill records and review reports", True)]),
    },
    "EMS-8.3": {
        "title": "Management of Hazardous Substances and Waste",
        "guidance": "Establish controls for hazardous substances and waste to prevent pollution.",
        "question": "Are hazardous substances and waste managed with appropriate controls?",
        "na_allowed": True,
        "scoring": _s(["No hazardous substance or waste management controls.", "Basic waste disposal only.",
                        "Waste procedures exist but hazardous inventory incomplete.",
                        "Comprehensive register with waste segregation and tracking.",
                        "Zero-waste strategy with circular economy principles."]),
        "evidence": _e([("Hazardous substance register and safety data sheets", True),
                         ("Waste management records including disposal certificates", True)]),
    },
    "EMS-9.1": {
        "title": "Monitoring, Measurement, Analysis and Evaluation",
        "guidance": "Monitor, measure, analyse, and evaluate environmental performance.",
        "question": "Is environmental performance monitored and compliance evaluated?",
        "na_allowed": False,
        "scoring": _s(["No environmental monitoring.", "Some data collected but not analysed.",
                        "Monitoring in place but compliance evaluation not formalised.",
                        "Performance monitored for significant aspects, compliance evaluated.",
                        "Real-time monitoring with automated data collection and dashboards."]),
        "evidence": _e([("Environmental monitoring plan", True), ("Compliance evaluation records", True)]),
    },
    "EMS-9.2": {
        "title": "Internal Audit",
        "guidance": "Conduct internal audits at planned intervals to verify EMS conformity.",
        "question": "Are internal environmental audits conducted at planned intervals?",
        "na_allowed": False,
        "scoring": _s(["No internal audit programme.", "Audits conducted sporadically.",
                        "Programme exists but coverage incomplete.",
                        "Audit programme with competent auditors and corrective actions tracked.",
                        "Risk-based programme with specialist auditors and trend analysis."]),
        "evidence": _e([("Internal audit programme and schedule", True),
                         ("Audit reports with findings and corrective actions", True)]),
    },
    "EMS-9.3": {
        "title": "Management Review",
        "guidance": "Top management shall review the EMS at planned intervals.",
        "question": "Does top management review the EMS with appropriate inputs and outputs?",
        "na_allowed": False,
        "scoring": _s(["No management review.", "Informal reviews without structured agenda.",
                        "Reviews conducted but environmental data not included.",
                        "Reviews at planned intervals with all required inputs and outputs.",
                        "Strategic reviews with data-driven insights and sustainability analysis."]),
        "evidence": _e([("Management review minutes with environmental agenda", True),
                         ("Evidence of action item completion", True)]),
    },
    "EMS-10.1": {
        "title": "Nonconformity and Corrective Action",
        "guidance": "Manage nonconformities with root cause analysis and corrective actions.",
        "question": "Are environmental nonconformities managed with corrective actions?",
        "na_allowed": False,
        "scoring": _s(["No nonconformity management.", "Nonconformities addressed reactively.",
                        "Corrective actions taken but impact mitigation not addressed.",
                        "Nonconformities documented, impacts mitigated, root cause analysed.",
                        "Integrated CAPA system with trend analysis and lessons-learned."]),
        "evidence": _e([("Nonconformity and corrective action procedure", True),
                         ("CAPA log with root cause analysis", True)]),
    },
    "EMS-10.2": {
        "title": "Continual Improvement",
        "guidance": "Continually improve the suitability, adequacy, and effectiveness of the EMS.",
        "question": "Does the organisation actively pursue continual improvement?",
        "na_allowed": False,
        "scoring": _s(["No continual improvement activities.", "Improvement occurs reactively only.",
                        "Some initiatives but not systematic.",
                        "Improvement programme with projects linked to objectives.",
                        "Culture of excellence with innovation and measurable trends."]),
        "evidence": _e([("Environmental improvement programme", True),
                         ("Evidence of completed improvement projects", True)]),
    },
    "EMS-10.3": {
        "title": "Pollution Prevention and Resource Efficiency",
        "guidance": "Implement measures to prevent pollution and promote resource efficiency.",
        "question": "Are pollution prevention and resource efficiency measures implemented?",
        "na_allowed": False,
        "scoring": _s(["No pollution prevention measures.", "Basic recycling only.",
                        "Some measures but not linked to targets.",
                        "Prevention measures at source with efficiency targets monitored.",
                        "Comprehensive sustainability programme with verified carbon reduction."]),
        "evidence": _e([("Pollution prevention and resource efficiency programme", True),
                         ("Resource consumption data and trend reports", True)]),
    },
}

SCOPING_QUESTIONS = [
    {"identifier": "ems-q1", "question_text": "Does the organisation handle, store, or use hazardous substances?",
     "answer_type": "yes_no", "options": None, "sort_order": 0},
    {"identifier": "ems-q2", "question_text": "Does the organisation have significant air emissions?",
     "answer_type": "yes_no", "options": None, "sort_order": 1},
    {"identifier": "ems-q3", "question_text": "Does the organisation generate hazardous or regulated waste streams?",
     "answer_type": "yes_no", "options": None, "sort_order": 2},
]

SCOPING_RULES = [
    {"question_identifier": "ems-q1", "trigger_answer": "Yes", "target_type": "criterion", "target_code": "EMS-8.3", "applicability_status": "applicable"},
    {"question_identifier": "ems-q1", "trigger_answer": "No", "target_type": "criterion", "target_code": "EMS-8.3", "applicability_status": "not_applicable"},
    {"question_identifier": "ems-q2", "trigger_answer": "Yes", "target_type": "criterion", "target_code": "EMS-9.1", "applicability_status": "applicable"},
    {"question_identifier": "ems-q2", "trigger_answer": "No", "target_type": "criterion", "target_code": "EMS-9.1", "applicability_status": "not_applicable"},
    {"question_identifier": "ems-q3", "trigger_answer": "Yes", "target_type": "criterion", "target_code": "EMS-10.3", "applicability_status": "applicable"},
    {"question_identifier": "ems-q3", "trigger_answer": "No", "target_type": "criterion", "target_code": "EMS-10.3", "applicability_status": "not_applicable"},
]
