"""Seed data for TM Risk Subjects, Templates, and Controls."""

RISK_SUBJECTS = [
    {
        "code": "RS01",
        "name": "Live Traffic / Vehicle Incursion",
        "icon": "🚗",
        "description": "Risks from moving vehicles entering or interacting with the work zone",
        "sort_order": 1,
        "risks": [
            {
                "code": "RS01-R01",
                "title": "Vehicle strikes worker in active work zone",
                "description": "A moving vehicle leaves the carriageway or ignores TTM controls and enters the work zone, striking a worker on foot.",
                "likelihood": 3,
                "severity": 5,
                "risk_level": "High",
                "causes": ["Driver inattention or distraction (phone use)", "Speeding through reduced speed zone", "Poor delineation of work zone boundaries", "Night works with inadequate advance warning", "Weather reducing driver visibility (rain, fog, glare)"],
                "consequences": ["Worker fatality", "Serious traumatic injury", "Multiple casualties if TMA or plant involved"],
                "legislation": ["Health and Safety at Work Act 2015 s36 (duty to manage risks)", "CoPTTM Part 3 — Work Zone Protection", "Land Transport Rule: Traffic Control Devices 2004"],
                "emergency_action": "Worker struck by vehicle: Call 111 immediately. Do not move injured person unless in immediate danger. STMS to halt traffic. Preserve scene. Notify management. WorkSafe NZ serious harm notification required — call 0800 030 040.",
                "copttm_ref": "CoPTTM Part 3, Section 4",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Close road to through traffic where operationally feasible and approved by RCA"},
                    {"hierarchy": "Substitute", "control": "Use remote-controlled or automated flagging devices instead of personnel in live lanes"},
                    {"hierarchy": "Isolate", "control": "Deploy Truck-Mounted Attenuator (TMA) on all sites with speed limit 80 km/h or above"},
                    {"hierarchy": "Isolate", "control": "Install water-filled or concrete barriers to physically separate work zone from traffic"},
                    {"hierarchy": "Isolate", "control": "Maintain minimum lateral clearance from live lane per CoPTTM Table 4-1"},
                    {"hierarchy": "Engineer", "control": "Install speed reduction signage in advance (graduated: 80→60→posted work zone speed)"},
                    {"hierarchy": "Engineer", "control": "Place advance warning signs at CoPTTM-required distances for the posted speed"},
                    {"hierarchy": "Engineer", "control": "Install delineators and cones at correct spacing for speed environment"},
                    {"hierarchy": "Engineer", "control": "Provide adequate lighting minimum 100 lux at work face for night works"},
                    {"hierarchy": "Admin", "control": "STMS to conduct pre-start site briefing covering vehicle incursion emergency escape routes"},
                    {"hierarchy": "Admin", "control": "Designate a lookout/spotter for all workers with backs to traffic"},
                    {"hierarchy": "Admin", "control": "Monitor live traffic speed compliance — pause work if repeated non-compliance observed"},
                    {"hierarchy": "Admin", "control": "All workers to know and practice escape route before work begins"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis vest or jacket meeting AS/NZS 4602.1:2011"},
                    {"hierarchy": "PPE", "control": "Safety boots meeting AS/NZS 2210:2009"},
                    {"hierarchy": "PPE", "control": "Hard hat (AS/NZS 1801) where overhead hazards also present"}
                ],
            },
            {
                "code": "RS01-R02",
                "title": "Rear-end collision at lane merge / taper",
                "description": "Vehicles failing to merge or stop in time cause rear-end collision at or approaching the work zone taper.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["Insufficient advance warning distance for the approach speed", "Queue length exceeds distance covered by advance signage", "Driver confusion at merge point", "Driver distraction or impairment"],
                "consequences": ["Injury to motorists", "Secondary collision involving workers or plant", "Plant or vehicle damage"],
                "legislation": ["CoPTTM Section 4 — Tapers and Transitions", "Land Transport Rule: Traffic Control Devices 2004"],
                "emergency_action": "Collision at taper: Call 111. STMS to assess casualties. Stop all traffic movement if required for emergency vehicle access. Do not disturb scene. Notify management and WorkSafe if serious harm.",
                "copttm_ref": "CoPTTM Section 4.3",
                "controls": [
                    {"hierarchy": "Substitute", "control": "Use Variable Message Signs (VMS) for dynamic queue warning ahead of static advance signs"},
                    {"hierarchy": "Isolate", "control": "Deploy TMA at the upstream end of a static queue when queue is forming"},
                    {"hierarchy": "Engineer", "control": "Calculate taper length using CoPTTM formula (L = V²/155 for speeds ≥60 km/h)"},
                    {"hierarchy": "Engineer", "control": "Place advance warning signs at minimum distances per CoPTTM Table 4-2 for posted speed"},
                    {"hierarchy": "Engineer", "control": "Install QUEUE AHEAD sign when queuing is occurring or likely"},
                    {"hierarchy": "Admin", "control": "TC to monitor queue length throughout shift and alert STMS if queue reaches advance sign"},
                    {"hierarchy": "Admin", "control": "STMS to adjust taper length or extend advance signage if queue exceeds planned length"},
                    {"hierarchy": "Admin", "control": "Consider stop-go batching to manage queue when continuous flow creates risk"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis for all personnel"}
                ],
            },
            {
                "code": "RS01-R03",
                "title": "Worker struck while setting up or packing down TTM",
                "description": "Workers on foot are exposed to live traffic during the setup or removal of cones, signs and devices.",
                "likelihood": 4,
                "severity": 4,
                "risk_level": "High",
                "causes": ["No protection in place during initial setup (first few devices)", "Worker positioning between vehicles and devices", "Rushing during pack-down especially at end of shift", "Poor communication between driver and crew on foot"],
                "consequences": ["Worker fatality or serious injury", "Vehicle damage"],
                "legislation": ["CoPTTM Part 2 — Procedures for Placing and Removing TTM", "HSWA 2015 s36"],
                "emergency_action": "Worker struck during setup/pack-down: Call 111. Stop all setup/removal activity. Do not move injured person. Notify WorkSafe (0800 030 040) if serious harm. Preserve scene.",
                "copttm_ref": "CoPTTM Part 2, Section 3",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Use rolling road closure or shadow vehicle for setup/pack-down where possible"},
                    {"hierarchy": "Isolate", "control": "Setup vehicle positioned to provide shadow protection during cone placement"},
                    {"hierarchy": "Engineer", "control": "Place advance warning signs first before any crew on foot in carriageway"},
                    {"hierarchy": "Admin", "control": "Follow CoPTTM setup sequence — advance signs before working area devices"},
                    {"hierarchy": "Admin", "control": "STMS to supervise all setup and pack-down — no rushing"},
                    {"hierarchy": "Admin", "control": "Pack-down to follow reverse sequence — remove working area last, advance signs first"},
                    {"hierarchy": "Admin", "control": "Dedicated driver maintains vehicle as protection shadow during all foot operations"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis at all times during carriageway operations"},
                    {"hierarchy": "PPE", "control": "Safety boots"}
                ],
            }
        ],
    },
    {
        "code": "RS02",
        "name": "Pedestrians & Footpaths",
        "icon": "🚶",
        "description": "Risks to pedestrians including footpath closures, diversions, and vulnerable road users",
        "sort_order": 2,
        "risks": [
            {
                "code": "RS02-R01",
                "title": "Pedestrian enters live traffic due to blocked footpath",
                "description": "Footpath is closed or obstructed by works forcing pedestrians onto the road or into vehicle paths.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["No alternative pedestrian route provided", "Diversion route unclear or unsigned", "Footpath closure signs removed or blown over", "Pedestrians taking shortcuts through work zone"],
                "consequences": ["Pedestrian struck by vehicle", "Serious injury or fatality", "Legal liability for PCBU"],
                "legislation": ["HSWA 2015 s36", "CoPTTM Part 6 — Pedestrian Management", "Local authority footpath closure permit requirements"],
                "emergency_action": "Pedestrian struck: Call 111. Provide first aid if trained. Do not move injured person. Notify WorkSafe if serious harm (0800 030 040). Notify management immediately.",
                "copttm_ref": "CoPTTM Part 6",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Maintain footpath access throughout works where at all possible"},
                    {"hierarchy": "Substitute", "control": "Provide protected temporary pedestrian path (hoarding/barriers) at same side as original footpath"},
                    {"hierarchy": "Isolate", "control": "If same-side path not possible, provide clearly signed and lit diversion to opposite footpath"},
                    {"hierarchy": "Engineer", "control": "Install PEDESTRIAN DIVERSION signs at each approach to closure with arrow directions"},
                    {"hierarchy": "Engineer", "control": "Ensure diversion route is suitable for mobility devices (prams, wheelchairs) — no kerb lips"},
                    {"hierarchy": "Engineer", "control": "Maintain lighting on diversion route for night works"},
                    {"hierarchy": "Admin", "control": "Obtain footpath closure permit from local RCA/Council before works begin"},
                    {"hierarchy": "Admin", "control": "Check diversion signage is in place and intact at each shift start"},
                    {"hierarchy": "Admin", "control": "Notify affected businesses and residents of closure and diversion route"},
                    {"hierarchy": "PPE", "control": "Workers managing pedestrian diversion: Class 3 Hi-Vis"}
                ],
            },
            {
                "code": "RS02-R02",
                "title": "Pedestrian falls into excavation or open work area",
                "description": "Unprotected excavations, trenches or open work areas adjacent to pedestrian areas create fall hazard.",
                "likelihood": 2,
                "severity": 4,
                "risk_level": "Medium",
                "causes": ["Inadequate barriers around excavation", "Barriers removed by third parties overnight", "Poor visibility at night", "Children or vulnerable people ignoring barriers"],
                "consequences": ["Fall injury — fractures, head injury", "Entrapment in trench", "Fatality if deep excavation"],
                "legislation": ["HSWA 2015 s36", "NZS 3910 — Conditions of Contract for Civil Works", "CoPTTM Part 6"],
                "emergency_action": "Person fallen into excavation: Call 111. Do not enter excavation if collapse risk. Provide reassurance to casualty. Await emergency services. Do not attempt to move if spinal injury possible.",
                "copttm_ref": "CoPTTM Part 6, WorkSafe Excavation Guide",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Backfill and reinstate excavation same day where operationally possible"},
                    {"hierarchy": "Isolate", "control": "Install rigid hoarding (not just cones) around all excavations adjacent to pedestrian areas"},
                    {"hierarchy": "Engineer", "control": "Install safety mesh or covering over trenches left overnight"},
                    {"hierarchy": "Engineer", "control": "Provide adequate lighting at excavation perimeter for night/low-visibility periods"},
                    {"hierarchy": "Admin", "control": "Inspect barriers at start of each shift and after any weather events"},
                    {"hierarchy": "Admin", "control": "Maintain site security — prevent unauthorized access"},
                    {"hierarchy": "PPE", "control": "Workers near open excavations: hard hat, safety boots, Class 3 Hi-Vis"}
                ],
            },
            {
                "code": "RS02-R03",
                "title": "Vulnerable road users (cyclists, mobility devices) at risk",
                "description": "Cyclists, e-scooter users, wheelchair users and pram users are inadequately provided for in TTM plans.",
                "likelihood": 3,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["TMP does not account for cycle lanes or shared paths", "Diversion routes have kerb lips or rough surfaces unsuitable for wheels", "Cyclists directed into live traffic lane without adequate separation", "Signage does not communicate alternative routing to cyclists"],
                "consequences": ["Cyclist collision with vehicle", "Mobility device user unable to navigate diversion — public complaint", "Regulatory non-compliance with disability access requirements"],
                "legislation": ["CoPTTM Part 6", "Human Rights Act 1993 (disability access)", "Local authority cycle network requirements"],
                "emergency_action": "Cyclist or mobility user injured: Call 111. Provide first aid if trained. Do not move person. Notify WorkSafe if serious harm.",
                "copttm_ref": "CoPTTM Part 6.4",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Maintain cycle lane access through works wherever possible"},
                    {"hierarchy": "Substitute", "control": "Provide separated temporary cycle path if permanent lane closed"},
                    {"hierarchy": "Engineer", "control": "Ensure all pedestrian/cycle diversions are kerb-ramp accessible"},
                    {"hierarchy": "Engineer", "control": "Install CYCLISTS DISMOUNT or CYCLE DIVERSION signs at each closure point"},
                    {"hierarchy": "Admin", "control": "TMP to include specific section on pedestrian and cycle management"},
                    {"hierarchy": "Admin", "control": "Consult with local council cycling team if major cycle route affected"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis for workers near cycle facilities"}
                ],
            }
        ],
    },
    {
        "code": "RS03",
        "name": "Manual Handling \u2014 Signs, Cones & Barriers",
        "icon": "💪",
        "description": "Musculoskeletal risks from lifting, carrying and placing TTM equipment",
        "sort_order": 3,
        "risks": [
            {
                "code": "RS03-R01",
                "title": "Musculoskeletal injury from repetitive cone/sign lifting",
                "description": "Repetitive lifting, carrying and placing of cones, signs, and water-filled barriers causes strain injuries.",
                "likelihood": 4,
                "severity": 3,
                "risk_level": "High",
                "causes": ["Poor lifting technique — bending from back not knees", "Overloading — carrying too many cones per trip", "Wet or slippery conditions making equipment heavier to handle", "Fatigue from long shifts", "No mechanical aids available"],
                "consequences": ["Lower back strain or injury", "Shoulder or rotator cuff injury", "Chronic musculoskeletal disorder", "Lost time injury"],
                "legislation": ["HSWA 2015 s36", "WorkSafe NZ Manual Handling Guidance 2016"],
                "emergency_action": "Worker reports back/shoulder pain: Stop the task immediately. Do not continue if pain is present. Arrange medical assessment. Record on incident register. Review manual handling method before resuming.",
                "copttm_ref": "N/A — WorkSafe manual handling guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Use vehicle-mounted cone dispensers/collectors for cone placement on high-volume routes"},
                    {"hierarchy": "Substitute", "control": "Use lighter-weight equipment where CoPTTM compliance allows (lighter cone bases in lower speed environments)"},
                    {"hierarchy": "Engineer", "control": "Use mechanical lifting aids for water barriers and heavy signs"},
                    {"hierarchy": "Admin", "control": "Manual handling training for all crew — correct technique before deployment"},
                    {"hierarchy": "Admin", "control": "Rotate tasks to vary physical demands across crew throughout shift"},
                    {"hierarchy": "Admin", "control": "Maximum 3 cones carried per person per trip — do not stack beyond safe limit"},
                    {"hierarchy": "Admin", "control": "Scheduled rest breaks — minimum per Employment Relations Act 2000 requirements"},
                    {"hierarchy": "PPE", "control": "Gloves for grip and hand protection when handling metal sign posts"},
                    {"hierarchy": "PPE", "control": "Safety boots with ankle support"}
                ],
            },
            {
                "code": "RS03-R02",
                "title": "Crush injury from falling or dropped signs / barriers",
                "description": "Heavy signs, posts or water barriers fall or are dropped during handling causing crush or impact injuries.",
                "likelihood": 2,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["Wet or slippery gloves reducing grip", "Over-reaching during placement from vehicle", "Unsecured load on vehicle shifting during transit", "Wind toppling unsecured sign frames"],
                "consequences": ["Foot/toe crush injury", "Hand or finger crush", "Head strike from falling sign"],
                "legislation": ["HSWA 2015 s36", "Land Transport Rule: Vehicle Dimensions and Mass 2016 (securing loads)"],
                "emergency_action": "Crush injury: Assess severity. If serious — call 111. Apply first aid. Do not remove heavy object without emergency services if limb entrapment. Notify WorkSafe if serious harm.",
                "copttm_ref": "N/A",
                "controls": [
                    {"hierarchy": "Engineer", "control": "Ensure all sign frames are ballasted correctly per manufacturer specifications"},
                    {"hierarchy": "Engineer", "control": "Secure all equipment on vehicles with straps or tie-downs before transit"},
                    {"hierarchy": "Admin", "control": "Two-person lifts required for all equipment over 16 kg"},
                    {"hierarchy": "Admin", "control": "Load securing check before departure from depot and job site"},
                    {"hierarchy": "PPE", "control": "Steel-toed safety boots (AS/NZS 2210) mandatory for all crew"},
                    {"hierarchy": "PPE", "control": "Gloves with good grip for all equipment handling"}
                ],
            }
        ],
    },
    {
        "code": "RS04",
        "name": "Night Works",
        "icon": "🌙",
        "description": "Additional risks specific to works conducted after dark or in low-visibility conditions",
        "sort_order": 4,
        "risks": [
            {
                "code": "RS04-R01",
                "title": "Reduced driver visibility increasing vehicle incursion risk",
                "description": "Darkness significantly reduces the time drivers have to respond to TTM controls, increasing incursion risk.",
                "likelihood": 3,
                "severity": 5,
                "risk_level": "High",
                "causes": ["Inadequate retroreflective or lit signing", "Cones without sleeves or lit tops", "Work lights creating glare for approaching drivers", "Workers not wearing retroreflective PPE"],
                "consequences": ["Worker struck by vehicle", "Head-on collision in contraflow", "Fatality"],
                "legislation": ["CoPTTM Part 3 — Night Works requirements", "HSWA 2015 s36"],
                "emergency_action": "Incident at night: Call 111. Activate hazard lights on all vehicles. Do not reduce lighting at scene until police clear it. Notify management.",
                "copttm_ref": "CoPTTM Part 3, Section 6 — Night Works",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Schedule works in daylight hours where possible to avoid night risk"},
                    {"hierarchy": "Engineer", "control": "All signs to be retroreflective Class 1 minimum, Class 2 preferred for night works"},
                    {"hierarchy": "Engineer", "control": "Cone sleeves (retroreflective) on all cones visible to approaching traffic at night"},
                    {"hierarchy": "Engineer", "control": "Install lit arrow boards or dynamic signs at key decision points"},
                    {"hierarchy": "Engineer", "control": "Provide task lighting at work face without creating forward glare for drivers"},
                    {"hierarchy": "Engineer", "control": "TMA required on all night works sites 80 km/h and above"},
                    {"hierarchy": "Admin", "control": "Night works-specific risk assessment completed before works begin"},
                    {"hierarchy": "Admin", "control": "Site inspection immediately before work commences to check all night-specific controls in place"},
                    {"hierarchy": "PPE", "control": "Class 3 retroreflective Hi-Vis (AS/NZS 4602.1) — mandatory for all crew"},
                    {"hierarchy": "PPE", "control": "Head torch for task work in work zone"}
                ],
            },
            {
                "code": "RS04-R02",
                "title": "Worker fatigue during night shift",
                "description": "Night shift work disrupts circadian rhythm leading to fatigue, reduced alertness and increased error rate.",
                "likelihood": 4,
                "severity": 3,
                "risk_level": "High",
                "causes": ["Extended shift duration beyond 10 hours", "Consecutive night shifts without adequate rest", "Workers commuting long distances before/after shift", "No fatigue management policy enforced"],
                "consequences": ["Worker error leading to incorrect TTM setup", "Worker falls asleep — collapse or vehicle accident commuting", "Reduced situational awareness increasing incursion exposure"],
                "legislation": ["HSWA 2015 s36", "Employment Relations Act 2000 (rest breaks)", "Land Transport (Driver Licensing) Rule 1999 (for driving post-shift)"],
                "emergency_action": "Worker appears unfit or incapacitated from fatigue: Remove from work zone immediately. Do not allow fatigued worker to drive. Arrange transport home. Record incident.",
                "copttm_ref": "N/A — WorkSafe Fatigue Guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Limit consecutive night shifts to maximum 3 before rest day where operationally possible"},
                    {"hierarchy": "Admin", "control": "Maximum 10-hour shifts for night works — enforce strictly"},
                    {"hierarchy": "Admin", "control": "Mandatory rest breaks: 10 min per 2 hours worked minimum"},
                    {"hierarchy": "Admin", "control": "STMS to monitor crew alertness throughout shift — send fatigued workers home"},
                    {"hierarchy": "Admin", "control": "Fatigue self-declaration: crew to advise STMS if unfit at start of shift"},
                    {"hierarchy": "Admin", "control": "Provide caffeinated drinks and snacks on site"},
                    {"hierarchy": "Admin", "control": "Buddy system — workers check on each other's alertness"}
                ],
            }
        ],
    },
    {
        "code": "RS05",
        "name": "Plant & Vehicle Operations",
        "icon": "🚛",
        "description": "Risks from operating or working near trucks, vans, TMAs and other mobile plant on site",
        "sort_order": 5,
        "risks": [
            {
                "code": "RS05-R01",
                "title": "Worker struck by reversing vehicle or plant",
                "description": "Worker on foot is struck by a reversing truck, van or plant in the work zone or depot.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["Driver blind spot obscuring worker", "No reversing alarm or camera fitted", "Worker not in driver's line of sight", "No spotter during reversing operations", "Work zone layout forcing reversing near workers"],
                "consequences": ["Worker struck — serious injury or fatality", "Equipment damage"],
                "legislation": ["HSWA 2015 s36", "WorkSafe NZ — Safer Farms / Plant Safety (principles apply)"],
                "emergency_action": "Worker struck by vehicle: Call 111. Do not move injured person. Stop all plant movement. Preserve scene. Notify WorkSafe if serious harm (0800 030 040).",
                "copttm_ref": "N/A — WorkSafe plant safety guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Design work zone layout to eliminate reversing wherever possible — drive-through layout preferred"},
                    {"hierarchy": "Engineer", "control": "All reversing vehicles to have functioning reversing alarm"},
                    {"hierarchy": "Engineer", "control": "Reversing cameras fitted to all vehicles where practicable"},
                    {"hierarchy": "Admin", "control": "Designated spotter required for all reversing operations near workers on foot"},
                    {"hierarchy": "Admin", "control": "Exclusion zone established — workers not to enter reversing path without signal from driver"},
                    {"hierarchy": "Admin", "control": "Clear communication protocol between driver and spotter (hand signals or radio)"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis mandatory — maximum visibility to drivers"}
                ],
            },
            {
                "code": "RS05-R02",
                "title": "TMA rear impact — operator injury",
                "description": "The TMA (Truck-Mounted Attenuator) is struck from behind by an errant vehicle. Operator inside cab may be injured.",
                "likelihood": 2,
                "severity": 4,
                "risk_level": "Medium",
                "causes": ["TMA positioned at incorrect distance behind work crew", "TMA not deployed/locked in operating position", "TMA operator not wearing seatbelt", "Errant vehicle at high speed — attenuator capacity exceeded"],
                "consequences": ["TMA operator injury from impact forces", "TMA vehicle propelled forward into work crew", "Vehicle write-off"],
                "legislation": ["CoPTTM Part 3 — TMA requirements", "NZTA TMA guidelines"],
                "emergency_action": "TMA struck: Check TMA operator first — call 111 if injured. Stop all work crew activity. Move crew to safe area. Assess structural integrity of TMA before resuming. Notify management and WorkSafe if serious harm.",
                "copttm_ref": "CoPTTM Part 3.5 — TMA Requirements",
                "controls": [
                    {"hierarchy": "Engineer", "control": "TMA deployed and locked in operating position before work crew exposed"},
                    {"hierarchy": "Engineer", "control": "TMA positioned to provide correct shadow zone coverage per CoPTTM"},
                    {"hierarchy": "Engineer", "control": "TMA meets NCHRP350 or MASH test level appropriate for site speed"},
                    {"hierarchy": "Admin", "control": "TMA operator must wear seatbelt at all times while parked in live traffic"},
                    {"hierarchy": "Admin", "control": "TMA daily pre-use inspection — attenuator, lights, strobe, arrow board"},
                    {"hierarchy": "Admin", "control": "TMA operator to remain in cab at all times while deployed in live lane"},
                    {"hierarchy": "PPE", "control": "Seatbelt — mandatory"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis when outside vehicle"}
                ],
            },
            {
                "code": "RS05-R03",
                "title": "Vehicle mechanical failure in live traffic",
                "description": "A work vehicle breaks down or has tyre failure while positioned in or adjacent to live traffic.",
                "likelihood": 2,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["Vehicle not maintained — worn tyres, poor brakes", "No pre-start vehicle inspection conducted", "Vehicle overloaded beyond rated capacity"],
                "consequences": ["Vehicle stops in live lane creating hazard", "Tyre blow-out causing loss of vehicle control", "Workers exposed while attempting roadside repair"],
                "legislation": ["HSWA 2015 s36", "Land Transport Rule: Vehicle Dimensions and Mass 2016", "Land Transport Rule: Frontal Impact 2001 (WoF compliance)"],
                "emergency_action": "Vehicle broken down in live lane: Activate hazard lights immediately. Call STMS. Call AA or tow company. Do not exit vehicle into live traffic unless safe to do so. If unable to move — call 111 to notify police.",
                "copttm_ref": "N/A",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Maintain all vehicles on scheduled service programme — no overdue services"},
                    {"hierarchy": "Engineer", "control": "Daily pre-start vehicle check: tyres, brakes, lights, fluids, WoF/CoF current"},
                    {"hierarchy": "Admin", "control": "Defective vehicle not to be used until repaired — tag out system"},
                    {"hierarchy": "Admin", "control": "Breakdown procedure: hazard lights, call STMS, do not attempt roadside repair in live lane"},
                    {"hierarchy": "Admin", "control": "All vehicles carry basic breakdown kit: warning triangles, first aid kit"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis if exiting vehicle in traffic environment"}
                ],
            }
        ],
    },
    {
        "code": "RS06",
        "name": "Adverse Weather Conditions",
        "icon": "⛈️",
        "description": "Risks created or worsened by rain, wind, heat, lightning and other weather events",
        "sort_order": 6,
        "risks": [
            {
                "code": "RS06-R01",
                "title": "High winds displacing TTM equipment into traffic",
                "description": "Strong winds blow over signs, cones or barriers into the live lane creating an uncontrolled road hazard.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["Lightweight sign frames with insufficient ballast", "Cones without weight rings in wind-exposed locations", "No weather monitoring during extended shifts"],
                "consequences": ["Sign or cone strikes moving vehicle — crash", "Motorist swerves to avoid debris — collision", "Worker struck while retrieving equipment"],
                "legislation": ["CoPTTM — equipment ballasting requirements", "HSWA 2015 s36"],
                "emergency_action": "Equipment in live lane: Do not retrieve without vehicle protection in place. Deploy shadow vehicle first. Retrieve equipment with crew protected. If immediate danger to motorists — call 111.",
                "copttm_ref": "CoPTTM equipment ballasting tables",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Suspend works during wind gusts exceeding safe operating thresholds for equipment in use"},
                    {"hierarchy": "Engineer", "control": "Ballast sign frames to manufacturer specification — double ballast in exposed locations"},
                    {"hierarchy": "Engineer", "control": "Use weighted cone rings on all cones in wind-exposed sites"},
                    {"hierarchy": "Engineer", "control": "Use water-filled barriers instead of cones at critical delineation points in high-wind areas"},
                    {"hierarchy": "Admin", "control": "Monitor weather forecast before every shift — check NIWA or MetService"},
                    {"hierarchy": "Admin", "control": "STMS to conduct equipment inspection if wind increases during shift"},
                    {"hierarchy": "Admin", "control": "Establish wind threshold for work suspension — communicate to all crew"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis with close-fitting design to reduce wind interference"}
                ],
            },
            {
                "code": "RS06-R02",
                "title": "Slippery surfaces — worker slip/trip/fall",
                "description": "Rain, morning dew or spilled materials make road surfaces slippery causing worker falls.",
                "likelihood": 3,
                "severity": 2,
                "risk_level": "Medium",
                "causes": ["Rain creating wet road surface", "Morning dew on road markings or painted surfaces", "Diesel or oil spill on road surface", "Uneven ground at road/verge interface"],
                "consequences": ["Worker slip/fall — sprained ankle, laceration", "Fall into live lane"],
                "legislation": ["HSWA 2015 s36"],
                "emergency_action": "Worker fallen: Assess for injury. If on road surface — move to safe area first. First aid. If head injury or loss of consciousness — call 111. Record incident.",
                "copttm_ref": "N/A",
                "controls": [
                    {"hierarchy": "Engineer", "control": "Use anti-slip matting at work areas where prolonged stationary work on slippery surface"},
                    {"hierarchy": "Admin", "control": "Crew briefed on slip hazards at pre-start — identify specific surfaces at that site"},
                    {"hierarchy": "Admin", "control": "Slow down task pace in wet conditions — do not rush"},
                    {"hierarchy": "PPE", "control": "Safety boots with slip-resistant sole (AS/NZS 2210) — minimum requirement"},
                    {"hierarchy": "PPE", "control": "Wet weather gear — waterproof jacket and pants — to prevent cold/wet fatigue"}
                ],
            },
            {
                "code": "RS06-R03",
                "title": "Heat stress and dehydration during summer works",
                "description": "Workers exposed to direct sun and high temperatures during outdoor works suffer heat stress.",
                "likelihood": 3,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["Extended outdoor work in high UV/temperature conditions", "No access to shade or water on work site", "Hi-Vis garments increasing heat load", "Physical exertion in heat"],
                "consequences": ["Heat exhaustion — dizziness, nausea, collapse", "Heat stroke — medical emergency", "Reduced worker alertness in traffic environment"],
                "legislation": ["HSWA 2015 s36", "WorkSafe NZ — Working in the heat guidance"],
                "emergency_action": "Heat stroke suspected (hot dry skin, confusion, loss of consciousness): Call 111 immediately. Move to shade. Apply cool wet cloths to neck, armpits, groin. Do not give fluids if unconscious.",
                "copttm_ref": "N/A — WorkSafe heat guidance",
                "controls": [
                    {"hierarchy": "Substitute", "control": "Schedule intensive physical work for early morning when temperatures are lower"},
                    {"hierarchy": "Engineer", "control": "Provide shade shelter (gazebo/canopy) at work zone rest area"},
                    {"hierarchy": "Admin", "control": "Free access to cool drinking water at all times — minimum 250 ml per hour per worker in heat"},
                    {"hierarchy": "Admin", "control": "Mandatory rest breaks in shade during high heat periods (above 28°C ambient)"},
                    {"hierarchy": "Admin", "control": "STMS to monitor crew for signs of heat stress — nausea, confusion, heavy sweating"},
                    {"hierarchy": "Admin", "control": "Buddy system — workers to check on each other"},
                    {"hierarchy": "PPE", "control": "Broad-brimmed hat or legionnaire cap under hard hat"},
                    {"hierarchy": "PPE", "control": "SPF 50+ sunscreen applied before shift and reapplied every 2 hours"},
                    {"hierarchy": "PPE", "control": "Lightweight breathable Hi-Vis where available"}
                ],
            }
        ],
    },
    {
        "code": "RS07",
        "name": "Electrical Hazards",
        "icon": "⚡",
        "description": "Risks from overhead power lines, underground cables and electrical equipment on site",
        "sort_order": 7,
        "risks": [
            {
                "code": "RS07-R01",
                "title": "Plant or equipment contact with overhead power lines",
                "description": "Arrow boards, sign posts, elevated equipment or vehicle loads contact live overhead power lines.",
                "likelihood": 2,
                "severity": 5,
                "risk_level": "High",
                "causes": ["Failure to identify overhead lines in site assessment", "Equipment raised without checking clearance height", "Vehicles with high loads (elevated signs, trailers) in line proximity"],
                "consequences": ["Electrocution of worker", "Fatality", "Fire from arcing"],
                "legislation": ["HSWA 2015 s36", "Electricity Act 1992", "WorkSafe NZ — Working near power lines guidance", "Minimum approach distances: lines up to 110kV — 4m; 110kV-220kV — 6m"],
                "emergency_action": "Contact with power lines: Do not touch the vehicle or person — stay back minimum 8m. Call 111 and network operator (Chorus/Vector/lines company). Wait for network operator to confirm lines de-energised before approaching.",
                "copttm_ref": "N/A — WorkSafe electrical safety guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Identify all overhead power lines in site assessment before any work begins"},
                    {"hierarchy": "Eliminate", "control": "Request line isolation from network operator if work within 4m of lines"},
                    {"hierarchy": "Substitute", "control": "Redirect vehicle routes to avoid passing under low power lines with tall loads"},
                    {"hierarchy": "Engineer", "control": "Install goal post height restriction barriers under low lines if vehicles must pass"},
                    {"hierarchy": "Admin", "control": "Dial Before You Dig (0800 248 344) for all sites involving any ground breaking"},
                    {"hierarchy": "Admin", "control": "Site induction to specifically identify overhead line locations and exclusion distances"},
                    {"hierarchy": "Admin", "control": "Spotter required when any work within 4m of overhead lines"},
                    {"hierarchy": "PPE", "control": "Insulating gloves for any work near electrical infrastructure — only qualified persons"}
                ],
            },
            {
                "code": "RS07-R02",
                "title": "Damage to underground electrical or gas services",
                "description": "Excavation or ground penetration damages buried electrical cables, gas mains, or telecommunications infrastructure.",
                "likelihood": 2,
                "severity": 4,
                "risk_level": "Medium",
                "causes": ["No service location check before ground penetration", "Services not accurately shown on as-built drawings", "Manual excavation drifting from permitted location"],
                "consequences": ["Electrocution from damaged cable", "Gas ignition and explosion", "Water main rupture", "Significant service disruption"],
                "legislation": ["HSWA 2015 s36", "Electricity Act 1992", "Gas Act 1992"],
                "emergency_action": "Cable or gas main struck: Stop all work immediately. Evacuate area minimum 50m for gas. Call 111 and relevant utility emergency line. Do not attempt to repair. Keep public away.",
                "copttm_ref": "N/A",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Avoid ground penetration entirely unless scope requires it"},
                    {"hierarchy": "Engineer", "control": "Dial Before You Dig (0800 248 344) — mandatory before any ground penetration"},
                    {"hierarchy": "Engineer", "control": "Service location scan (CAT scanner) before manual or mechanical excavation"},
                    {"hierarchy": "Admin", "control": "Hand-dig trial hole to confirm service locations before mechanical excavation"},
                    {"hierarchy": "Admin", "control": "Mark confirmed service locations with paint or stakes before any works"},
                    {"hierarchy": "Admin", "control": "Maintain minimum 500mm hand-dig zone around confirmed service locations"}
                ],
            }
        ],
    },
    {
        "code": "RS08",
        "name": "School Zones & High Pedestrian Areas",
        "icon": "🏫",
        "description": "Additional risks in areas with high numbers of children, elderly or vulnerable pedestrians",
        "sort_order": 8,
        "risks": [
            {
                "code": "RS08-R01",
                "title": "Child enters work zone or live lane during school peak hours",
                "description": "Children, who are less predictable than adults, enter the work zone or live lane especially during school start/finish times.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["Work scheduled without consideration of school peak hours", "Attractive nuisance — children curious about machinery", "Inadequate physical barriers at work zone perimeter", "No specific communication to school about works"],
                "consequences": ["Child struck by vehicle or plant", "Serious injury or fatality", "Significant public/media and legal impact"],
                "legislation": ["HSWA 2015 s36", "Land Transport Rule: Traffic Control Devices 2004 — school zone requirements", "CoPTTM Part 6"],
                "emergency_action": "Child in work zone or struck: Call 111 immediately. Stop all works. Notify school and management. WorkSafe notification required for serious harm. Do not move child if serious injury suspected.",
                "copttm_ref": "CoPTTM Part 6 — school zones",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Schedule disruptive works outside school peak hours (8–9am and 2:30–3:30pm) where possible"},
                    {"hierarchy": "Isolate", "control": "Install solid hoarding or continuous barrier — cones alone are insufficient near school zones"},
                    {"hierarchy": "Admin", "control": "Notify school principal before works begin — agree communication to parents if access affected"},
                    {"hierarchy": "Admin", "control": "Provide a dedicated crew member as pedestrian management officer during school peak hours"},
                    {"hierarchy": "Admin", "control": "Coordinate with school patrol or crossing guard if works affect their area"},
                    {"hierarchy": "PPE", "control": "All crew in Class 3 Hi-Vis — high visibility is especially important near children"}
                ],
            }
        ],
    },
    {
        "code": "RS09",
        "name": "Intersections & Signalised Crossings",
        "icon": "🚦",
        "description": "Risks specific to works at or near intersections, roundabouts and signalised pedestrian crossings",
        "sort_order": 9,
        "risks": [
            {
                "code": "RS09-R01",
                "title": "Conflict between TTM controls and traffic signal phasing",
                "description": "TTM stop-go or lane closures conflict with existing traffic signal phases creating confusion and potential collision.",
                "likelihood": 3,
                "severity": 4,
                "risk_level": "High",
                "causes": ["TTM implemented without coordinating with signal operator", "Traffic signals not modified to accommodate lane closure", "Drivers receiving contradictory instructions from signals vs TTM"],
                "consequences": ["Vehicle collision at intersection", "Worker or pedestrian struck", "Significant traffic disruption"],
                "legislation": ["CoPTTM Part 5 — works at signalised intersections", "NZTA/AT signal operations requirements"],
                "emergency_action": "Collision at intersection: Call 111. Stop all TTM operations until police arrive. Do not adjust signals without operator authority. Notify management.",
                "copttm_ref": "CoPTTM Part 5",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Avoid works at signalised intersections during peak traffic periods where possible"},
                    {"hierarchy": "Engineer", "control": "Coordinate with signal operator (AT or NZTA) to modify signal phasing before works begin"},
                    {"hierarchy": "Engineer", "control": "Temporary signal override or manual control where approved"},
                    {"hierarchy": "Admin", "control": "TMP to specifically address signal coordination — approved by RCA"},
                    {"hierarchy": "Admin", "control": "Qualified STMS to manage TTM at signalised intersections — not TC-only"},
                    {"hierarchy": "Admin", "control": "Confirm signal changes are active before lane closure is implemented"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis"}
                ],
            }
        ],
    },
    {
        "code": "RS10",
        "name": "Motorway / State Highway Works",
        "icon": "🛣️",
        "description": "Additional risks specific to high-speed motorway and state highway environments",
        "sort_order": 10,
        "risks": [
            {
                "code": "RS10-R01",
                "title": "Worker exposure at high-speed site (100 km/h+)",
                "description": "At motorway speeds the time available for drivers to react to TTM controls is significantly reduced, substantially increasing strike risk.",
                "likelihood": 3,
                "severity": 5,
                "risk_level": "High",
                "causes": ["Insufficient advance warning distances for 100 km/h", "TMA not deployed or inadequate test level", "Workers exposed beyond TMA shadow zone", "Night works without enhanced lighting and signing"],
                "consequences": ["Worker fatality — high energy impact", "Multi-vehicle collision", "Large-scale emergency response"],
                "legislation": ["CoPTTM Part 3 — high speed requirements", "NZTA State Highway TTM requirements", "HSWA 2015 s36"],
                "emergency_action": "Serious incident on motorway: Call 111. Deploy additional hazard warnings upstream immediately. Stop all traffic if possible. Coordinate with NZTA traffic operations centre. WorkSafe notification for serious harm.",
                "copttm_ref": "CoPTTM Part 3 — High Speed Sites",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Full carriageway closure with contraflow or detour route for all high-risk work on motorways"},
                    {"hierarchy": "Isolate", "control": "TMA mandatory — MASH TL-3 minimum for 100 km/h+ sites"},
                    {"hierarchy": "Isolate", "control": "Concrete or water-filled barriers for any works lasting more than one shift"},
                    {"hierarchy": "Engineer", "control": "Advance warning signs at mandatory distances for 100 km/h: minimum 500m first sign"},
                    {"hierarchy": "Engineer", "control": "Speed reduction: 100→80→60→posted work zone speed with enforcement present"},
                    {"hierarchy": "Engineer", "control": "Variable speed limit signs (VSL) where available on NZTA network"},
                    {"hierarchy": "Admin", "control": "NZTA pre-approval required — TMP submitted and approved before any works"},
                    {"hierarchy": "Admin", "control": "Police presence for all high-risk motorway closures — coordinate in advance"},
                    {"hierarchy": "Admin", "control": "Crew escape routes identified and drilled before work begins"},
                    {"hierarchy": "PPE", "control": "Class 3 Hi-Vis mandatory — retroreflective for night works"},
                    {"hierarchy": "PPE", "control": "Safety boots — steel-capped"}
                ],
            }
        ],
    },
    {
        "code": "RS11",
        "name": "Dust, Fumes & Air Quality",
        "icon": "💨",
        "description": "Respiratory risks from dust, vehicle exhaust, asphalt fumes and other airborne contaminants",
        "sort_order": 11,
        "risks": [
            {
                "code": "RS11-R01",
                "title": "Worker respiratory exposure to traffic exhaust and asphalt fumes",
                "description": "Prolonged exposure to vehicle exhaust emissions and hot asphalt fumes in confined or enclosed work zones.",
                "likelihood": 3,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["Work in heavy traffic corridor with high diesel vehicle volume", "Confined work zone trapping exhaust fumes", "Hot asphalt laying adjacent to workers", "Extended shift duration in high-exposure location"],
                "consequences": ["Short-term: headache, nausea, dizziness", "Long-term: respiratory disease, carcinogen exposure (PAHs in asphalt)", "Aggravation of asthma or existing respiratory conditions"],
                "legislation": ["HSWA 2015 s36", "WorkSafe NZ — Workplace Exposure Standards (WES)", "Asphalt fumes: WES-TWA applies per WorkSafe WES document"],
                "emergency_action": "Worker experiencing breathing difficulty or dizziness: Move to fresh air immediately. Sit down. If symptoms persist — call 111. Do not return to work zone until assessed.",
                "copttm_ref": "N/A — WorkSafe WES guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Minimise time workers spend stationary in exhaust-heavy zones — rotate positions"},
                    {"hierarchy": "Substitute", "control": "Position rest/break area upwind of exhaust sources"},
                    {"hierarchy": "Admin", "control": "Worker health surveillance for those regularly exposed to asphalt fumes — annual lung function check"},
                    {"hierarchy": "Admin", "control": "Limit shift duration in high-fume environments — rotate crews"},
                    {"hierarchy": "PPE", "control": "P2 respirator for asphalt/fume-intensive tasks"},
                    {"hierarchy": "PPE", "control": "P1 dust mask minimum where dust is generated"}
                ],
            }
        ],
    },
    {
        "code": "RS12",
        "name": "Environmental \u2014 Flooding & Stormwater",
        "icon": "🌊",
        "description": "Risks from flooding, stormwater runoff and environmental damage during works",
        "sort_order": 12,
        "risks": [
            {
                "code": "RS12-R01",
                "title": "Flooding of work zone creating unsafe conditions",
                "description": "Rapid water level rise in work zone during storm event traps workers or makes zone unsafe.",
                "likelihood": 2,
                "severity": 4,
                "risk_level": "Medium",
                "causes": ["Works near waterway or low-lying drainage area", "Blocked stormwater drain increasing water accumulation", "Rapid weather event not forecast", "No flood monitoring procedure"],
                "consequences": ["Worker swept away or trapped by floodwater", "Vehicle flotation or damage", "Damage to road infrastructure"],
                "legislation": ["HSWA 2015 s36", "Resource Management Act 1991 (sediment/stormwater discharge)"],
                "emergency_action": "Flooding in work zone: Evacuate all workers to high ground immediately. Do not attempt to drive through floodwater. Call STMS and management. Call 111 if workers trapped.",
                "copttm_ref": "N/A",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Avoid scheduling works near waterways during high rainfall season where possible"},
                    {"hierarchy": "Admin", "control": "Check weather and flood warnings before every shift near waterways — MetService and regional council flood alerts"},
                    {"hierarchy": "Admin", "control": "Establish a flood trigger level and evacuation procedure before works begin"},
                    {"hierarchy": "Admin", "control": "STMS has authority to suspend works and evacuate without requiring management approval in flood emergency"},
                    {"hierarchy": "Engineer", "control": "Install sediment controls (silt fence, rock bund) to prevent stormwater contamination"}
                ],
            }
        ],
    },
    {
        "code": "RS13",
        "name": "Aggression & Hostile Road Users",
        "icon": "😡",
        "description": "Verbal or physical aggression from frustrated road users or members of the public",
        "sort_order": 13,
        "risks": [
            {
                "code": "RS13-R01",
                "title": "Verbal or physical assault on traffic management crew",
                "description": "Frustrated, impaired or aggressive road users verbally or physically assault crew members, particularly TCs managing stop-go.",
                "likelihood": 3,
                "severity": 3,
                "risk_level": "Medium",
                "causes": ["Road user frustration with delays", "Impaired or volatile road users", "TC positioned without support from other crew", "Isolated work location", "Night works — increased intoxicated driver prevalence"],
                "consequences": ["Worker psychological trauma", "Physical assault — injury", "Worker stepping into live lane while avoiding aggressor"],
                "legislation": ["HSWA 2015 s36 (psychosocial risks)", "Crimes Act 1961 — assault", "WorkSafe NZ — Preventing and responding to workplace violence"],
                "emergency_action": "Physical assault: Withdraw to safe distance immediately. Call 111. Do not attempt to restrain aggressor. Call STMS. Record vehicle details if possible. Do not resume TC duties until police attend. Debrief and psychological support offered to affected worker.",
                "copttm_ref": "N/A — WorkSafe violence prevention guidance",
                "controls": [
                    {"hierarchy": "Eliminate", "control": "Use automated stop-go systems or signals instead of personnel where available"},
                    {"hierarchy": "Isolate", "control": "TC to maintain physical distance from driver's window — do not approach vehicles"},
                    {"hierarchy": "Admin", "control": "De-escalation training for all TC and STMS roles"},
                    {"hierarchy": "Admin", "control": "TC never to work in complete isolation — buddy within visual range at all times"},
                    {"hierarchy": "Admin", "control": "Radio check-in protocol — TC to call STMS every 30 minutes during long stop-go operations"},
                    {"hierarchy": "Admin", "control": "All crew briefed: withdraw, do not engage — call STMS and police (111) for physical aggression"},
                    {"hierarchy": "Admin", "control": "Incident reporting: all aggressive incidents to be recorded, no minimising"}
                ],
            }
        ],
    },
    {
        "code": "RS14",
        "name": "Emergency Services Access",
        "icon": "🚑",
        "description": "Risks that the work zone obstructs or delays emergency service vehicle access",
        "sort_order": 14,
        "risks": [
            {
                "code": "RS14-R01",
                "title": "Work zone blocks emergency vehicle access to incident or property",
                "description": "Road closure or lane reduction prevents ambulance, fire or police vehicles from reaching an incident or property in a timely manner.",
                "likelihood": 2,
                "severity": 4,
                "risk_level": "Medium",
                "causes": ["TMP does not include emergency access plan", "TC not briefed on emergency vehicle procedure", "Full road closure without alternative emergency access route", "Communication failure between TC and STMS when emergency vehicle arrives"],
                "consequences": ["Delayed emergency response — life-threatening", "Legal liability", "Reputational damage"],
                "legislation": ["HSWA 2015 s36", "Fire and Emergency NZ Act 2017", "Land Transport Act 1998"],
                "emergency_action": "Emergency vehicle approaching: TC to immediately move all moveable barriers to create access. Alert STMS by radio. Record time and service (Police/Ambulance/Fire). After emergency vehicle passes — confirm safe before reinstating closure.",
                "copttm_ref": "CoPTTM — Emergency Access Requirements",
                "controls": [
                    {"hierarchy": "Engineer", "control": "TMP to include documented emergency access plan — must be approved by RCA"},
                    {"hierarchy": "Admin", "control": "All crew briefed on emergency vehicle procedure before works begin"},
                    {"hierarchy": "Admin", "control": "TC briefed: on blue lights approach — immediately open gap in closure without waiting for STMS instruction"},
                    {"hierarchy": "Admin", "control": "Notify FENZ and ambulance communications of road closure location, duration, and emergency access route"},
                    {"hierarchy": "Admin", "control": "Maintain minimum 3m emergency access lane through any partial closure where possible"}
                ],
            }
        ],
    },
]