"""Tōtika Category 2 — Health & Safety template seed data.

Contains all 54 criteria (MB1–MB54) with sections, scoring anchors,
evidence checklists, guidance text, questions, tips, and na_allowed flags.
Extracted from the existing single-file audit tool.
"""

TEMPLATE_NAME = "T\u014dtika Category 2 \u2014 Health & Safety"
TEMPLATE_VERSION = "1.0"

# Sections in display order
SECTIONS = [
    {
        "name": "Leadership & Commitment",
        "codes": ["MB1","MB2","MB3","MB4","MB5","MB6"],
    },
    {
        "name": "Processes to Support H&S",
        "codes": ["MB7","MB8","MB9","MB10","MB11","MB12","MB13","MB14"],
    },
    {
        "name": "Skills, Training, Competency & Supervision",
        "codes": ["MB15","MB16","MB17","MB18","MB19"],
    },
    {
        "name": "Event Reporting, Recording & Investigation",
        "codes": ["MB20","MB21","MB22","MB23"],
    },
    {
        "name": "Emergency Management & Response",
        "codes": ["MB24","MB25"],
    },
    {
        "name": "Communication, Engagement & Participation",
        "codes": ["MB26","MB27","MB28"],
    },
    {
        "name": "Hazard/Risk Identification & Effective Controls",
        "codes": ["MB29","MB30","MB31","MB32","MB33"],
    },
    {
        "name": "Occupational Health & Wellness",
        "codes": ["MB34","MB35","MB36"],
    },
    {
        "name": "Health & Safety Inspections",
        "codes": ["MB37","MB38"],
    },
    {
        "name": "Sub-contractors & PCBUs",
        "codes": ["MB39","MB40","MB41","MB42","MB43"],
    },
    {
        "name": "Plant & Equipment",
        "codes": ["MB44","MB45"],
    },
    {
        "name": "Hazardous Substances",
        "codes": ["MB46","MB47","MB48","MB49"],
    },
    {
        "name": "H&S Performance History",
        "codes": ["MB50","MB51","MB52","MB53","MB54"],
    },
]

# All 54 criteria (MB1-MB54)
CRITERIA = {
    "MB1": {
        "title": "H&S Policy",
        "guidance": "The organisation shall have a signed policy reviewed at least annually, signed/dated by top management, showing how the business is organised to deliver H&S (responsibilities & accountabilities). The policy shall commit to: legal compliance; good practice; consulting with workers on H&S matters; continuous improvement.",
        "question": "Do you have a H&S policy that sets out leadership and commitment requirements for good H&S practice?",
        "na_allowed": False,
        "tip": "Policy must be reviewed within the last 12 months. Undated or unsigned policies will not score above 0.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Policy with only one element of the minimum requirements."},
            {"score": 2, "description": "Policy with only two elements of the minimum requirements."},
            {"score": 3, "description": "Policy reviewed <12 months, signed/dated by top management, covers responsibilities/accountabilities, commits to legal compliance, good practice, worker consultation, and continuous improvement."},
            {"score": 4, "description": "Meets score 3 AND demonstrates how the policy is implemented in practice."},
        ],
        "evidence": [
            {
                "text": "H&S Policy document — signed and dated by General Manager",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Policy includes: legal compliance, good practice, worker consultation, continuous improvement commitments",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Evidence of annual review date on policy",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Responsibilities and accountabilities set out in policy or HSMS",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB2": {
        "title": "H&S Policy Communication",
        "guidance": "The organisation shall show how the policy is communicated to workers (including when it is updated) and confirm workers understand it.",
        "question": "How do you communicate the H&S policy to workers and confirm they understand it?",
        "na_allowed": False,
        "tip": "Must score 3 on MB1 before you can score 3 here.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Has a policy but no evidence of communication."},
            {"score": 2, "description": "Policy has not scored a 3 in MB1."},
            {"score": 3, "description": "Induction or training/briefing records with worker sign-off confirming understanding. Records available."},
            {"score": 4, "description": "Demonstrates innovation in how the policy is communicated and implemented."},
        ],
        "evidence": [
            {
                "text": "Induction sign-off records showing workers have received the policy",
                "age_label": "< 12 months old (current workers)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Toolbox talk records referencing policy communication/review",
                "age_label": "Recent — within 12 months",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Worker acknowledgement forms or sign-off sheets",
                "age_label": "Current staff",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB3": {
        "title": "Accountabilities",
        "guidance": "The organisation has defined H&S accountabilities for key management roles and workers. Identify the most senior manager with overall H&S accountability.",
        "question": "Are H&S accountabilities/responsibilities allocated to management roles in your organisation?",
        "na_allowed": False,
        "tip": "You need two distinct role descriptions — not two copies of the same. Could be GM + STMS.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but some gaps; evidence supports most of the requirement."},
            {"score": 3, "description": "Accountabilities defined; two different job descriptions (or similar) with specific H&S elements provided; most senior manager identified."},
            {"score": 4, "description": "All governance and leadership roles have specific H&S responsibilities, objectives linked to performance and remuneration."},
        ],
        "evidence": [
            {
                "text": "At least two job descriptions with H&S accountabilities written in (e.g. GM, STMS)",
                "age_label": "Current roles",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Statement identifying most senior person accountable for H&S (e.g. General Manager)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Organisational chart or responsibilities matrix",
                "age_label": "Current",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB4": {
        "title": "Dealing with H&S Issues",
        "guidance": "The organisation has processes to deal with work-related H&S issues including tracking agreed actions to completion.",
        "question": "Does your business have processes to deal with work-related H&S issues including tracking actions to completion?",
        "na_allowed": False,
        "tip": "The example issue must show the full lifecycle — raised → assigned → tracked → closed.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps; evidence supports most of requirement."},
            {"score": 3, "description": "Procedure/process shows how issues are raised and tracked to completion; example of issue managed with description, affected parties, actions, tracking, and outcome."},
            {"score": 4, "description": "Includes a feedback loop mechanism with an implemented confidential H&S reporting system."},
        ],
        "evidence": [
            {
                "text": "Documented procedure/process for raising and tracking H&S issues (e.g. Action Tracking Register — REG001)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Example of a real H&S issue managed: description, who affected, how managed, actions assigned, completion evidence, outcome",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Action tracking register showing open/closed items",
                "age_label": "< 12 months",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB5": {
        "title": "Demonstrating Active Commitment",
        "guidance": "Senior leaders actively demonstrate their commitment to H&S of workers.",
        "question": "Do senior leaders of your organisation actively and positively demonstrate their commitment to H&S?",
        "na_allowed": False,
        "tip": "Evidence must be RECENT — aged records won't satisfy this criterion.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Evidence of: H&S as agenda item at management meetings; senior manager engagement in field; H&S committee involvement; setting and monitoring H&S performance indicators. Recent evidence required for all."},
            {"score": 4, "description": "Supported by two concurrent safety climate surveys (12 weeks apart) showing positive worker perceptions of management commitment."},
        ],
        "evidence": [
            {
                "text": "Management meeting minutes with H&S as standing agenda item",
                "age_label": "< 6 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Evidence of senior manager in-field H&S engagement (e.g. site visit records, toolbox talk sign-offs)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "H&S performance indicators set and reviewed by leadership",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "H&S Committee minutes or similar worker engagement records",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB6": {
        "title": "Considering H&S Impacts in Decisions",
        "guidance": "Senior leaders actively consider H&S impacts when making business decisions.",
        "question": "Do senior leaders actively consider H&S impacts when making business decisions?",
        "na_allowed": False,
        "tip": "Could be a purchasing decision (new vehicle, equipment), operational change, or site/project approval.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Example of business decision where H&S impact was considered: description of decision, potential H&S impacts, who affected, decision made to manage, success achieved."},
            {"score": 4, "description": "Wellbeing and H&S are integrated into all senior management and board decisions."},
        ],
        "evidence": [
            {
                "text": "Documented example of a business decision (project, CAPEX, major change) where H&S impacts were assessed",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Risk assessment or decision record showing H&S consideration",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": False,
            },
        ],
    },
    "MB7": {
        "title": "Documented HSMS and Procedures",
        "guidance": "The organisation has a documented H&S management system and procedures covering core H&S elements.",
        "question": "Do you have a documented HSMS and procedures/processes covering core H&S elements?",
        "na_allowed": False,
        "tip": "The INDEX document is key evidence here — it shows comprehensive HSMS coverage.",
        "scoring": [
            {"score": 0, "description": "No documented procedures."},
            {"score": 1, "description": "Some documented procedures but missing all required by Core Criteria."},
            {"score": 2, "description": "Some documented procedures but missing some required."},
            {"score": 3, "description": "HSMS documented with statement of coverage; list of all documented processes/procedures covering minimum Core Criteria elements. Each section in Core Criteria has supporting documentation."},
            {"score": 4, "description": "Innovation in how procedures are developed, implemented, and reviewed — with worker participation."},
        ],
        "evidence": [
            {
                "text": "HSMS document (SOP001 v2.1 or equivalent)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Document register / index of all H&S procedures (INDEX v1.1)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Confirmation that all Core Criteria sections have supporting procedures",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB8": {
        "title": "Competent H&S Advice",
        "guidance": "The organisation accesses and uses competent H&S advice. Construction contractors must mark NA Required if Principal Contractor.",
        "question": "Do you and your workers have access to competent H&S advice?",
        "na_allowed": False,
        "tip": "Note: H&S advisor does NOT need professional accreditation to satisfy score 3 (per v3.1.2). However, score 4 does require HASANZ membership.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Named advisor/s; internal/external; area of expertise; qualifications/professional registration; example of use for H&S decision."},
            {"score": 4, "description": "Internal/external H&S advisor holds at least Professional level membership of a HASANZ member body or international equivalent."},
        ],
        "evidence": [
            {
                "text": "Name, contact, and qualifications of H&S advisor (e.g. CyberCX, IC Safety Solutions, or named individual)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Evidence of when/why H&S advice was sought and how it was applied",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Copy of advisor's professional registration or qualification (if applicable)",
                "age_label": "Current / valid",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB9": {
        "title": "Resourcing H&S",
        "guidance": "The organisation plans and budgets for H&S and provides workers time and capability to apply H&S processes.",
        "question": "How does your organisation plan and budget for H&S and provide workers time/capability for H&S processes?",
        "na_allowed": False,
        "tip": "Score 4 specifically requires evidence of mental health/wellbeing budget — aligned with MB36.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Budget described (who sets it, methodology, who approves, what it covers); worker time allocation for training and H&S activities described."},
            {"score": 4, "description": "Demonstrates prioritised operational H&S expenditure AND budget for worker mental health and wellbeing."},
        ],
        "evidence": [
            {
                "text": "H&S budget documentation or description of H&S expenditure planning (who sets it, who approves, what it covers)",
                "age_label": "Current financial year",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Description of time allocated to H&S training, planning (JSA/TA), inspections, audits",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Evidence of budget for mental health/wellbeing (e.g. EAP subscription, MATES in Construction)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB10": {
        "title": "Site Specific Health & Safety Plans",
        "guidance": "The organisation develops site/service specific H&S plans (SSSPs) where the scope of work/project requires it. NA Required if Principal Contractor.",
        "question": "When working on a client's site do you develop site-specific health and safety plans (SSSPs)?",
        "na_allowed": True,
        "tip": "Must be site/project specific — a generic HSMS will not satisfy this. Traffic Management Plan (TMP) + SSSP elements count.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Recent SSSP example; site/project specific (not generic); covers: scope/phases, H&S accountabilities, hazard/risk management, training/competency, incident reporting, sub-contractor management, emergency response, inspection/audit."},
            {"score": 4, "description": "Shows how front-line workers contribute to development of site/project specific plans."},
        ],
        "evidence": [
            {
                "text": "Recent SSSP (site or service specific — not a copy of generic HSMS)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "SSSP covers all 8 required elements: scope, accountabilities, hazard management, training, incident reporting, sub-contractors, emergency response, inspections",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB11": {
        "title": "Continuous Improvement",
        "guidance": "The organisation has processes in place to review and improve all its H&S processes.",
        "question": "How do you ensure H&S is continually improved within your organisation?",
        "na_allowed": False,
        "tip": "Annual HSMS reviews, corrective actions from audits, and lessons learned from incidents all count as improvement examples.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Continuous improvement process described; two examples of improvements made within the last two years (description, how initiated, when/how made, benefits)."},
            {"score": 4, "description": "Uses learning teams, appreciative inquiry, HOP, HPE or similar to engage front-line workers in improvement."},
        ],
        "evidence": [
            {
                "text": "Two documented examples of H&S improvements made in last 2 years — each with: description, trigger, implementation date, benefits",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Documented continuous improvement process (e.g. HSMS annual review, corrective action system)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB12": {
        "title": "H&S Performance Goals",
        "guidance": "The organisation has processes in place to set H&S goals/objectives.",
        "question": "Does your organisation set H&S goals/objectives?",
        "na_allowed": False,
        "tip": "Objectives must be measurable (e.g. zero notifiable events, 100% inductions, all certifications current).",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes how goals are set, current goals/objectives, how tracked; evidence of goals being in place (e.g. meeting minutes, plans)."},
            {"score": 4, "description": "H&S strategy developed with allocation of responsibility and accountability outside H&S team/advisor roles."},
        ],
        "evidence": [
            {
                "text": "Documented H&S objectives/goals (SOP001 §13 or equivalent)",
                "age_label": "Current / annual",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Meeting minutes or plan showing H&S objectives discussed or set",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Tracking mechanism showing progress against each objective",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB13": {
        "title": "Monitoring H&S Performance",
        "guidance": "The organisation has processes in place to monitor H&S performance.",
        "question": "How does your organisation monitor its H&S performance?",
        "na_allowed": False,
        "tip": "Lead indicators are proactive (things done to prevent harm); lag indicators are reactive (harm that has occurred).",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes lead and lag indicators; how reported; frequency; responsible person; who receives reports. Two most recent H&S performance reports provided."},
            {"score": 4, "description": "H&S performance monitored using methods other than injury frequency rates."},
        ],
        "evidence": [
            {
                "text": "Two most recent H&S performance reports (lead + lag indicators)",
                "age_label": "< 3 months old (most recent)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Documented framework showing lead indicators (inspections, toolbox talks, training) and lag indicators (incidents, LTIs, notifiable events)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Evidence of who receives/reviews reports (GM, management meeting)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB14": {
        "title": "H&S Audit",
        "guidance": "The organisation has processes in place to audit its H&S systems and processes on a regular basis.",
        "question": "Does your organisation have a procedure/process in place for conducting HSMS audits on a regular basis?",
        "na_allowed": False,
        "tip": "The audit report is mandatory evidence — an undocumented audit will not satisfy this criterion.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure; states: frequency, who arranges, who carries out, who reviews, how corrective actions captured and implemented. Copy of HSMS audit within last two years."},
            {"score": 4, "description": "Top management formally reviews HSMS at least annually."},
        ],
        "evidence": [
            {
                "text": "HSMS audit procedure document",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Completed HSMS audit report",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Corrective actions from last audit with completion status (REG001)",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": False,
            },
            {
                "text": "Evidence of top management annual review of HSMS (e.g. management meeting minutes)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB15": {
        "title": "Training and Competence Processes",
        "guidance": "The organisation has a documented process for the training and competency of workers to ensure they can work safely.",
        "question": "Do you have a documented process for the training and competency of workers to ensure they can work safely?",
        "na_allowed": False,
        "tip": "The training register must show ALL workers — not just a sample.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure; training matrix (H&S training by role); training register (worker name, type of training, date completed, refresher dates)."},
            {"score": 4, "description": "Shows in-field verification of skill is applied."},
        ],
        "evidence": [
            {
                "text": "Documented training and competency procedure",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Training matrix showing H&S training required by role (REG002 or similar)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Training register per worker: type of training, date completed, refresher dates",
                "age_label": "Current records",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB16": {
        "title": "Induction",
        "guidance": "The organisation shall show how employees and contractors are provided with H&S induction to the organisation and how site/work area inductions are carried out and recorded.",
        "question": "Do you have a worker induction program that covers employees and contractors and inducts them into the workplace and/or worksites?",
        "na_allowed": False,
        "tip": "You need BOTH company-level and site-level induction evidence. Missing either drops score to 2.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Some records of company induction OR site inductions (not both)."},
            {"score": 2, "description": "Records of both company and site inductions but not on training register."},
            {"score": 3, "description": "Induction procedure; shows who receives, when, content (policy, responsibilities, hazards/risks, emergencies, training, incidents, worker participation); how records held; three recent completed induction records."},
            {"score": 4, "description": "Can evidence inductions at company and project level with content of inductions."},
        ],
        "evidence": [
            {
                "text": "Induction procedure document (may be part of training procedure)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Three recently completed induction records (F0001 or similar) — signed by worker and induction supervisor",
                "age_label": "< 12 months old (recent hires)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Training register showing induction completed for all current workers",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Site-specific induction records (F0006 / pre-start briefing records)",
                "age_label": "Recent (last 3 months)",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB17": {
        "title": "Foundation Training and Assessment",
        "guidance": "The organisation shall provide evidence that all workers have completed appropriate foundation H&S training. Construction contractors must also have a Foundation H&S Knowledge Assessment independent of the trainer (v3.1.4: training and assessment must be independent when using external provider).",
        "question": "Have your workers completed foundation H&S training (and for construction: an independent foundation knowledge assessment)?",
        "na_allowed": True,
        "tip": "v3.1.4 update (Dec 2024): Training and assessment MUST be independent when using an external provider. Evidence of this independence is now required.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Evidence of foundation H&S training for some workers."},
            {"score": 2, "description": "Evidence of training and assessment for some workers."},
            {"score": 3, "description": "Training register shows foundation H&S training completed for all workers; construction contractors: independent knowledge assessment completed; external providers: evidence of independence between training and assessment."},
            {"score": 4, "description": "Digital competency records per worker showing foundational training, independent assessment, site induction records, and level of competency."},
        ],
        "evidence": [
            {
                "text": "Training register showing foundation H&S training for ALL workers (e.g. NZQA unit standards, ConstructSafe, STMS/TMO/TC certifications)",
                "age_label": "Current (check expiry dates)",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Foundation knowledge assessment records — must be independent from training provider",
                "age_label": "Current (as per certification cycle)",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Evidence of independence between trainer and assessor where external provider used (v3.1.4 requirement)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB18": {
        "title": "Hazardous Work Training, Licenses and Certifications",
        "guidance": "All workers required to do specifically hazardous work have appropriate training and/or required licenses or certifications. NA Possible if no hazardous work undertaken.",
        "question": "Have workers required to carry out hazardous work been provided with appropriate training and/or hold required licenses/certifications?",
        "na_allowed": True,
        "tip": "For TTM: STMS, TMO, and TC certifications are the primary evidence. All must be current and not expired.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "List of hazardous work identified; required training/licence/certification for each; training register shows specialist training completed."},
            {"score": 4, "description": "Shows how hazardous work training is applied and monitored for efficacy."},
        ],
        "evidence": [
            {
                "text": "List of hazardous work activities (e.g. live traffic exposure, TMA operation, TMP implementation, night works)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Training register showing specialist licenses/certs for each hazardous work type (e.g. STMS, TMO, TC current certs — REG003)",
                "age_label": "Current — check expiry dates",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Copies of current STMS/TMO/TC certificates for all deployed workers",
                "age_label": "Valid — not expired",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB19": {
        "title": "Supervision of Vulnerable Workers",
        "guidance": "The organisation shows how workers under training, young workers, and other vulnerable workers are appropriately supervised and coached.",
        "question": "Describe how young, new, and other vulnerable workers are appropriately supervised and coached on the job.",
        "na_allowed": False,
        "tip": "Competency level system in SOP001 §11 maps to levels 1–5. Workers at Level 1 require active supervision on site.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Worker supervision provided but not structured to vulnerable groups."},
            {"score": 2, "description": "Vulnerable workers identified but no coherent plan."},
            {"score": 3, "description": "Covered in training procedure; on-the-job supervision process for workers not yet competent; records/evidence of this supervision."},
            {"score": 4, "description": "Competency levels identified; pathway process for workers to progress from direct to remote supervision."},
        ],
        "evidence": [
            {
                "text": "Supervision policy/procedure covering new starters, young workers, workers under training",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Records of on-job training/supervision activities for vulnerable workers (e.g. signed training records, buddy system sign-offs)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Training matrix showing competency levels and supervision requirements by level (REG002)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB20": {
        "title": "Event Recording, Reporting and Investigation Procedure",
        "guidance": "The organisation shall document an H&S event recording, reporting, and investigation process.",
        "question": "Do you have a documented procedure for event recording, reporting, and investigation?",
        "na_allowed": False,
        "tip": "If there are no incidents, note that on the form — a nil-incident history is valid. You still need the documented procedure.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Reporting is evident but no follow-up/learning/investigation."},
            {"score": 2, "description": "Policy/process exists but no evidence it is a current activity."},
            {"score": 3, "description": "Documented procedure plus two most recent event/incident report examples."},
            {"score": 4, "description": "Confidential reporting process for all workers with feedback loop. Investigation/learning involves workers and avoids individual blame."},
        ],
        "evidence": [
            {
                "text": "Documented incident recording, reporting, and investigation procedure (SOP001 §6)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Two most recent event/incident report examples (F0008 or equivalent)",
                "age_label": "< 2 years old (most recent available)",
                "age_class": "age-2y",
                "required": True,
            },
        ],
    },
    "MB21": {
        "title": "Investigation",
        "guidance": "The organisation demonstrates that they investigate all significant H&S events including high potential near misses.",
        "question": "Do you investigate all significant H&S events including high potential near misses?",
        "na_allowed": False,
        "tip": "Near misses should also be investigated — not just actual injuries. Nil incidents? Show near miss investigation records.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Process exists but little evidence of investigations being carried out."},
            {"score": 2, "description": "Some incidents are investigated."},
            {"score": 3, "description": "Copies of two recently completed investigation reports showing root cause analysis (not just individual actions)."},
            {"score": 4, "description": "Investigations by a person trained and competent in investigations methodology."},
        ],
        "evidence": [
            {
                "text": "Two completed investigation reports (more detailed than incident reports; shows root cause analysis)",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Investigation procedure or reference to procedure in HSMS",
                "age_label": "Current",
                "age_class": "age-na",
                "required": False,
            },
            {
                "text": "Evidence investigations cover root causes — not just individual worker actions",
                "age_label": "Per incident",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB22": {
        "title": "WorkSafe Notification",
        "guidance": "The organisation demonstrates that they understand notification requirements to WorkSafe NZ.",
        "question": "When are you required to notify WorkSafe NZ of a notifiable event?",
        "na_allowed": False,
        "tip": "CRITICAL: Wording must say \"as soon as possible\" — not \"immediately\". SOP001 §6, REF001 v1.1, and F0008 must all be consistent.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "N/A"},
            {"score": 2, "description": "N/A"},
            {"score": 3, "description": "Notifiable work and event requirements covered in procedure or description; shows when the organisation may need to notify WorkSafe NZ of a notifiable event."},
            {"score": 4, "description": "N/A"},
        ],
        "evidence": [
            {
                "text": "Procedure or documented statement describing: what constitutes a notifiable event (death, notifiable injury/illness, dangerous incident); when to notify (as soon as possible); how to notify (phone 0800 030 040 / worksafe.govt.nz); who is responsible (GM)",
                "age_label": "Current — must use \"as soon as possible\" wording",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "REF001 (HSaW Act Reference Guide) showing notifiable event definitions",
                "age_label": "Current version",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB23": {
        "title": "Communication and Follow-up from Investigations",
        "guidance": "The organisation demonstrates that they follow-up investigations with corrective actions, record findings, and communicate learnings to workers.",
        "question": "How do you ensure learnings from investigations are translated to improved work processes via corrective actions and worker communication?",
        "na_allowed": False,
        "tip": "You need to show the full loop: incident → investigation → corrective actions → tracked to closure → communicated to workers.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Policy/process exists but no evidence it is done."},
            {"score": 2, "description": "Policy/process exists; no recent evidence this is done."},
            {"score": 3, "description": "Describes how corrective actions are identified, recorded, and tracked to completion; how workers are informed of improvements. For the two MB21 investigations, corrective action evidence and completion provided."},
            {"score": 4, "description": "Workers involved in developing and implementing improvements."},
        ],
        "evidence": [
            {
                "text": "For the two MB21 investigation examples: evidence of agreed corrective actions and their completion status (REG001)",
                "age_label": "Current / closed out",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Toolbox talk records showing investigation learnings communicated to workers",
                "age_label": "Following each incident",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Corrective action tracking register showing open/closed items",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB24": {
        "title": "Emergency Processes",
        "guidance": "The organisation has documented processes for general emergency management and response.",
        "question": "Do you have documented emergency procedures covering general emergencies workers may be exposed to on your site/s?",
        "na_allowed": False,
        "tip": "For TTM context: include vehicle collision response, road rage/assault protocols, and medical emergencies in the field.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Procedure missing reasonably foreseeable emergency scenarios."},
            {"score": 2, "description": "Covers most likely emergencies but insufficient detail for meaningful worker response."},
            {"score": 3, "description": "Documented procedure covering: fire, earthquake, medical event, tsunami (if relevant), verbal/physical assault (if relevant), bomb threat (if relevant)."},
            {"score": 4, "description": "Regular testing of emergency responses and associated improvements."},
        ],
        "evidence": [
            {
                "text": "Emergency management procedure covering all reasonably foreseeable scenarios (SOP001 §9)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Emergency contacts list including 111, Poison Centre, Power/Gas, Chorus (SOP001 §9)",
                "age_label": "Current/verified",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Evidence of emergency procedure communication to workers (induction records, toolbox talks)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB25": {
        "title": "Specialist Emergency Response",
        "guidance": "The organisation has emergency response processes for specific/project sites or specialist higher risk work activities. NA Possible if no higher risk activities and always works under client/PC emergency plan.",
        "question": "Does your business develop emergency plans for client sites/projects as well as for specialist higher risk work activities?",
        "na_allowed": True,
        "tip": "NA Possible if you always work under a Principal Contractor's site emergency plan. Provide evidence of this if claiming NA.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes process for developing site/project emergency plan; copy of a site/project emergency plan; copy of a higher risk activity specialist emergency plan (or NA Possible evidence)."},
            {"score": 4, "description": "Plans connected to business continuity plan; plans practiced and pressure-tested."},
        ],
        "evidence": [
            {
                "text": "Site/project-specific emergency plan example",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Higher risk activity specialist emergency plan (e.g. high-speed road works, night works, TMA deployment)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB26": {
        "title": "Open Communication",
        "guidance": "The organisation actively promotes open communication on H&S with workers.",
        "question": "How does your organisation create an environment to support open communication with workers on H&S?",
        "na_allowed": False,
        "tip": "Examples must show actual communication events with outcomes — not just a statement that communication occurs.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Two examples (within last 2 years) of open H&S communication in action — each with: time/place/participants/type, summary of communication, outcome."},
            {"score": 4, "description": "Demonstrates how workers are encouraged to share \"bad news\" with management without fear of retribution."},
        ],
        "evidence": [
            {
                "text": "Two examples of open H&S communication in action (e.g. near-miss raised by worker and acted on, toolbox talk discussion and outcome)",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Policy statement, poster, or induction reference promoting open communication",
                "age_label": "Current",
                "age_class": "age-na",
                "required": False,
            },
            {
                "text": "Toolbox talk records showing two-way discussion (not just lecture)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB27": {
        "title": "Worker Engagement and Participation",
        "guidance": "The organisation has means to encourage and enable workers to engage and participate in H&S. NA Possible.",
        "question": "Do you have a documented procedure/process that encourages workers to engage and participate in H&S matters?",
        "na_allowed": True,
        "tip": "Toolbox talks count if they show genuine two-way participation — not just announcement of decisions already made.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Understanding of worker participation but no evidence of activity."},
            {"score": 2, "description": "Evidence of participation activity but no supporting policy."},
            {"score": 3, "description": "Documented procedure covering: H&S committee terms of reference; tools/processes for worker consultation; how workers are involved in H&S decision-making. Evidence it is applied (e.g. H&S committee minutes)."},
            {"score": 4, "description": "Trained safety representatives with evidence of them undertaking their function."},
        ],
        "evidence": [
            {
                "text": "Worker consultation procedure (SOP001 §7) showing triggers, method, minimum 48-hour response window, outcome communication",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "H&S committee meeting minutes OR toolbox talk records showing worker participation (not just attendance)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Example of a H&S decision where worker input changed the outcome",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": False,
            },
        ],
    },
    "MB28": {
        "title": "Meetings",
        "guidance": "The organisation holds regular/structured meetings with workers (including contractors) where H&S matters are discussed.",
        "question": "Do you have regular meetings with workers where H&S matters are discussed and workers can raise issues?",
        "na_allowed": False,
        "tip": "For TTM operations: daily pre-starts at job start are expected. Monthly management meetings and quarterly H&S reviews are also appropriate.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Evidence of minimal H&S meetings, far below expectations."},
            {"score": 2, "description": "Evidence available but falls short of expected frequency."},
            {"score": 3, "description": "Describes type, frequency, nature of meetings with workers; frequency appropriate for operation (prestart/toolbox daily, weekly or monthly management); evidence of these meetings occurring."},
            {"score": 4, "description": "Meets minimum AND demonstrates innovation in how workers discuss H&S matters."},
        ],
        "evidence": [
            {
                "text": "Pre-start briefing records (F0006) — dated, signed by participants, H&S topics recorded",
                "age_label": "< 2 weeks old (most recent)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Management/operations meeting minutes showing H&S as agenda item",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Toolbox talk records from last month",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB29": {
        "title": "Hazard/Risk Identification and Risk Control Processes",
        "guidance": "The organisation documents how it identifies hazards/risks and selects effective controls (applying hierarchy). Evidence of this occurring in practice required.",
        "question": "Do you have a documented procedure for the identification of hazards and management of their risk/s?",
        "na_allowed": False,
        "tip": "Must cover BOTH safety hazards AND occupational health hazards (noise, UV, fumes, musculoskeletal etc). Generic risk matrix alone is not sufficient.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic Hazard identification response with significant gaps."},
            {"score": 2, "description": "Hazard analysis and control processes partially addressed."},
            {"score": 3, "description": "Documented procedure covering: responsibilities, coverage of all org areas, identification methods (physical/work activity/occupational health), hierarchy of control, regular review. Current hazard/risk register provided. Two recent hazard/risk identification examples."},
            {"score": 4, "description": "Hazards prioritised; critical controls communicated and monitored for effectiveness."},
        ],
        "evidence": [
            {
                "text": "Hazard/risk identification and control procedure",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Current hazard/risk register (REG005 or similar)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Two recent examples of hazard/risk identification in practice (e.g. two site JSAs, two pre-start hazard identification records)",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
        ],
    },
    "MB30": {
        "title": "Hazard/Risk Control Communication",
        "guidance": "The organisation provides evidence of how hazard/risk controls are communicated to those they protect and that they are understood.",
        "question": "How do you communicate hazards/risks and their controls to your workers and confirm they understand?",
        "na_allowed": False,
        "tip": "Key method for TTM: pre-start briefing (F0006) where site-specific hazards and controls for the day are communicated and signed off.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes how communication occurs (induction, meetings, publications) and how worker understanding is confirmed; evidence this is happening."},
            {"score": 4, "description": "Comprehensive mechanism ensuring critical hazard/risk information communicated to all workers."},
        ],
        "evidence": [
            {
                "text": "Induction records showing hazard/risk controls communicated and signed off by workers",
                "age_label": "Per new starter",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Pre-start/toolbox talk records showing hazard-specific briefings",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Worker sign-off confirming understanding of site/task specific controls (e.g. JSA sign-off)",
                "age_label": "Per job",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB31": {
        "title": "Hazard/Risk Control Monitoring",
        "guidance": "The organisation provides evidence of how controls are monitored so they remain effective.",
        "question": "How do you monitor/review controls for your hazards/risks to ensure they are still effective?",
        "na_allowed": False,
        "tip": "F0005 (Site Review Report) completed during each job is the primary evidence for control monitoring in TTM.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes: monitoring/review activity (inspections, post-incident review, register reviews); who responsible; how completion confirmed and recorded; what happens when control is no longer effective."},
            {"score": 4, "description": "Assurance framework for critical controls with governance aspect."},
        ],
        "evidence": [
            {
                "text": "Site inspection records (F0005) showing control verification",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Process for updating hazard register when controls are found ineffective",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Post-incident review records showing control re-assessment",
                "age_label": "Per incident",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB32": {
        "title": "Safe Work Instructions",
        "guidance": "The organisation has effective methods to provide instructions on how to carry out work in a healthy and safe manner for both higher risk routine and non-routine activities.",
        "question": "Do you produce written work instructions, JSAs, Task Analysis, SWMS, and/or SOPs for the work you do?",
        "na_allowed": False,
        "tip": "Traffic Management Plans (TMPs) with embedded risk controls can contribute, but at least one JSA/TA covering specific work activities is expected.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Description of when/how written instructions produced (appropriate to risk profile); copies of two: JSA, TA, SOP, or SWMS."},
            {"score": 4, "description": "Front-line workers contribute to development and improvement of these instructions."},
        ],
        "evidence": [
            {
                "text": "Two recent JSAs/TAs/SWMSs/SOPs for work activities",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Description of when safe work instructions are produced (routine vs. non-routine)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB33": {
        "title": "PPE",
        "guidance": "The organisation demonstrates appropriate PPE is provided free to workers, checked/maintained, and workers are trained in correct use.",
        "question": "Are all workers provided with appropriate PPE, is it regularly checked/maintained, and are workers trained in its correct use?",
        "na_allowed": False,
        "tip": "For TTM: high-vis vests, safety boots, hard hats, gloves, eye protection and hearing protection are the standard PPE set.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Procedure covering appropriate PPE; list of all PPE provided; for two items: how type decided, how workers know when/how to use, storage management, condition checking; evidence of PPE management."},
            {"score": 4, "description": "Technical specifications for PPE; front-line workers consulted on PPE specification and use."},
        ],
        "evidence": [
            {
                "text": "List of all PPE currently provided to workers",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "PPE management procedure or description (how selected, how maintained, how checked)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "PPE inspection/replacement records (REG004 or similar)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Training records showing workers trained in correct PPE use",
                "age_label": "Per new starter / annual refresh",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB34": {
        "title": "Process for Monitoring of Health Risk",
        "guidance": "The organisation demonstrates they have identified occupational health hazards/risks and documented how appropriate health monitoring/surveillance is implemented. NA Possible if no health hazard exposures.",
        "question": "Have you identified occupational health hazards/risks that require health monitoring/surveillance, and do you carry this out?",
        "na_allowed": True,
        "tip": "For TTM workers: UV exposure (outdoor work), noise (traffic/machinery), and vehicle vibration are typical occupational health hazards to monitor.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "List of identified health hazards requiring monitoring; describes what monitoring is done, who has it, who completes it, when, and what is reported/actioned."},
            {"score": 4, "description": "Occupational health/hygiene specialist advice sought and applied."},
        ],
        "evidence": [
            {
                "text": "List of identified occupational health hazards (e.g. noise, UV exposure, vehicle vibration, dust, fumes, musculoskeletal)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Health monitoring records (e.g. hearing tests, musculoskeletal assessments) where applicable",
                "age_label": "< 2 years old (annual schedule)",
                "age_class": "age-2y",
                "required": False,
            },
            {
                "text": "Description of health monitoring process: what done, who has it, who conducts, when, follow-up",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB35": {
        "title": "Drugs and Alcohol",
        "guidance": "The organisation has a drug and alcohol policy.",
        "question": "Does your organisation have a workplace drug and alcohol policy?",
        "na_allowed": False,
        "tip": "The policy must specify the testing types — a general statement about not working impaired is not sufficient.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Policy document showing: stance on D&A; types of testing (pre-employment, post-incident, reasonable cause, random); post-incident testing; if random, how workers selected, frequency, % of workforce."},
            {"score": 4, "description": "Demonstrates how the organisation supports and rehabilitates workers with non-negative results."},
        ],
        "evidence": [
            {
                "text": "Drug and Alcohol Policy (POL001 or equivalent)",
                "age_label": "< 12 months old (reviewed)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Policy covers: D&A stance, testing types (pre-employment, post-incident, random/cause), testing process, consequences",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Testing records (if D&A testing is carried out — redacted for privacy)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB36": {
        "title": "Stress, Fatigue and Mental Wellbeing",
        "guidance": "Construction Contractors Only: Organisation has processes to manage work-related stress, fatigue and mental wellbeing. Must be actively engaged with Mates in Construction, Mates4Life or equivalent suicide prevention programme including General Awareness Training at all levels.",
        "question": "How does your organisation manage work-related stress, fatigue, and mental wellbeing?",
        "na_allowed": False,
        "tip": "CRITICAL GAP (zero-score risk): Must provide active engagement evidence for MATES in Construction — a statement of intent is not sufficient. Annual General Awareness Training records are mandatory.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes: senior leader education/training on stress/wellbeing/fatigue; how stress/fatigue considered in work planning; how mental wellbeing managed (identifying changes, positive environments). Evidence of active engagement with Mates in Construction / Mates4Life / equivalent including General Awareness Training at all levels."},
            {"score": 4, "description": "Formal fatigue management system with one example of fatigue/stress addressed in planning AND one example of mental wellbeing intervention."},
        ],
        "evidence": [
            {
                "text": "POL007 Mental Health & Wellbeing Policy and/or POL002 Fatigue Management Policy",
                "age_label": "< 12 months old (reviewed)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "MATES in Construction engagement evidence (registration, delivery records for General Awareness Training)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Evidence of Mates in Construction General Awareness Training completed by workers at all levels",
                "age_label": "< 12 months old (annual)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Description of how stress/fatigue is managed during work planning (roster management, rotation, hours off between shifts)",
                "age_label": "Current practice",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "EAP evidence (subscription confirmation, details provided to workers at induction)",
                "age_label": "Current",
                "age_class": "age-1y",
                "required": False,
            },
            {
                "text": "Example of work-related stress/fatigue addressed in planning or one mental wellbeing intervention (for score 4)",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": False,
            },
        ],
    },
    "MB37": {
        "title": "Worksite H&S Inspection Processes",
        "guidance": "The organisation has documented processes detailing how work sites are physically inspected. NA Possible.",
        "question": "Do you have a documented procedure for the physical inspection of worksites (other than offices)?",
        "na_allowed": True,
        "tip": "Two F0005 records from two different jobs/sites within the last month are the minimum. Corrective action status (open/closed) must be shown.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure covering: physical environment checks, safe worker behaviour checks, identifying/recording hazards, corrective action management, frequency. Two recent completed workplace safety inspections with corrective action status."},
            {"score": 4, "description": "Shows how workers and H&S representatives are engaged in inspection activity."},
        ],
        "evidence": [
            {
                "text": "Worksite inspection procedure (SOP001 §10)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Two recent completed Site Review Reports (F0005) with corrective action status",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Inspection checklist (F0007 vehicle/TMA pre-use check) records",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB38": {
        "title": "Frequency of Inspections",
        "guidance": "The organisation demonstrates how often worksite inspections are carried out and explains why that frequency is appropriate for the organisation. NA Possible.",
        "question": "How often do you carry out worksite inspections and why is this viewed as an appropriate frequency?",
        "na_allowed": True,
        "tip": "For TTM: document that checks occur at job setup AND every 2 hours during live-traffic operations. The rationale (dynamic conditions) must be stated.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Frequency described (at start of every job, daily, weekly, fortnightly, monthly, other) AND reasoning appropriate for the nature of the operation provided."},
            {"score": 4, "description": "Safety representatives, managers, and other leaders have specific objectives for contributing to these activities."},
        ],
        "evidence": [
            {
                "text": "Documented statement of inspection frequency with rationale (SOP001 §10 Rationale and Process)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "F0005 records showing frequency in practice (e.g. at start of each job AND 2-hourly on active TTM sites)",
                "age_label": "< 1 month old",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB39": {
        "title": "Contractor Management Process",
        "guidance": "The organisation documents a process for managing sub-contractors. NA Possible if sub-contractors clearly not engaged.",
        "question": "Do you have a documented procedure for the management of sub-contractors?",
        "na_allowed": True,
        "tip": "Score 4 explicitly rewards use of Tōtika for sub-contractor pre-qualification — note this in your process.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure covering: prequalification, contractor selection, requirements setting, pre-commencement (induction, SSSP sign-off), contractor monitoring, audit and review."},
            {"score": 4, "description": "Demonstrates use of Tōtika as part of contractor management processes."},
        ],
        "evidence": [
            {
                "text": "Sub-contractor management procedure",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB40": {
        "title": "Sub-contractor Engagement (Pre-qualification)",
        "guidance": "The organisation ensures all sub-contractors have completed a recognised H&S pre-qualification assessment. NA Possible if sub-contractors clearly not engaged.",
        "question": "Do you pre-qualify (H&S) each sub-contractor prior to engagement to confirm they have an appropriate HSMS?",
        "na_allowed": True,
        "tip": "If you don't engage sub-contractors, select N/A and provide the justification.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure confirms sub-contractors are pre-qualified; two examples of recent sub-contractor H&S pre-qualification."},
            {"score": 4, "description": "All sub-contractors on the Tōtika register."},
        ],
        "evidence": [
            {
                "text": "Two recent sub-contractor H&S pre-qualification examples",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Tōtika register entries for sub-contractors (for score 4)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB41": {
        "title": "Cooperation, Communication and Consultation with Sub-contractors",
        "guidance": "The organisation demonstrates how it communicates, consults, and co-operates with sub-contractors on H&S. NA Possible.",
        "question": "Do you have processes to ensure you communicate and work with sub-contractors on H&S to ensure work is coordinated?",
        "na_allowed": True,
        "tip": "NA applies if sub-contractors not engaged. Otherwise, SSSP sign-off and pre-start briefing records are the primary evidence.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Covers: how minimum H&S requirements are set with sub-contractors; how they are inducted; communication processes/methods; how work activity is coordinated. Evidence provided."},
            {"score": 4, "description": "Top management regularly and formally discusses H&S matters with sub-contractor top management."},
        ],
        "evidence": [
            {
                "text": "Evidence of sub-contractor induction into H&S programme",
                "age_label": "Per engagement",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Communication records with sub-contractors on H&S (e.g. pre-starts, SSSP sign-off, toolbox talks)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB42": {
        "title": "Sub-contractor Performance Monitoring",
        "guidance": "The organisation shows how sub-contractor performance is monitored and how ongoing learning and improvement is achieved. NA Possible.",
        "question": "Do you regularly monitor your sub-contractors' H&S performance and provide feedback?",
        "na_allowed": True,
        "tip": "NA applies if sub-contractors not engaged.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Covers: physical inspection, observation of workers/activity, assessment against JSA/SWMS, audit against SSSP, incident information collection/review. Frequency and reasoning. Evidence provided."},
            {"score": 4, "description": "Suite of lead indicators collaboratively agreed with sub-contractors."},
        ],
        "evidence": [
            {
                "text": "Sub-contractor inspection/audit records",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "Feedback provided to sub-contractors on H&S performance",
                "age_label": "Per monitoring cycle",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB43": {
        "title": "Cooperation, Communication and Consultation with Other PCBUs",
        "guidance": "The organisation demonstrates how it communicates, consults, and co-ordinates activities with other PCBUs it works with or near. NA Required if Principal Contractor (asked in PC01).",
        "question": "Do you have processes to consult, communicate, and coordinate activities with other organisations you work with or near?",
        "na_allowed": True,
        "tip": "For TTM: coordination with Councils, NZTA, Principal Contractors, and utility companies counts as multi-PCBU management.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Covers: planning to avoid negative impacts between organisations, how each does work safely, who else is affected, information exchange, worker communication across organisations, emergency procedure co-ordination, shared facilities."},
            {"score": 4, "description": "Top management regularly meets other PCBU top management to discuss/collaborate on H&S."},
        ],
        "evidence": [
            {
                "text": "Process for coordinating H&S with other PCBUs on shared work sites",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Evidence of PCBU communication on H&S (e.g. joint pre-starts, coordination meetings, shared site safety plans)",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB44": {
        "title": "Maintenance",
        "guidance": "The organisation documents a process to ensure appropriate plant and equipment maintenance. NA Possible if plant and equipment clearly not used.",
        "question": "Do you have a procedure or documented process for the appropriate maintenance of plant and/or equipment you use?",
        "na_allowed": True,
        "tip": "F0007 (Vehicle/TMA pre-use inspection checklist) completed before each deployment is the primary ongoing evidence.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Documented procedure; maintenance registers for: mobile plant/equipment, vehicles, lifting equipment, safety equipment. Register shows: item, date serviced, met service requirements, maintenance needs, next service date."},
            {"score": 4, "description": "Assessment system established to an appropriate standard (e.g. AS/NZS 4024.1201:2014)."},
        ],
        "evidence": [
            {
                "text": "Plant and equipment maintenance procedure",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Vehicle maintenance register showing last service, result, next service due",
                "age_label": "< 3 months old (most recent entries)",
                "age_class": "age-1y",
                "required": True,
            },
            {
                "text": "TMA and safety equipment maintenance/inspection records (REG004 or F0007)",
                "age_label": "< 1 month old (pre-use checks)",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB45": {
        "title": "Operation of Plant and Equipment",
        "guidance": "The organisation demonstrates how plant and equipment operations are effectively managed and monitored. NA Possible.",
        "question": "Do you have processes and systems for managing and monitoring plant and equipment operations?",
        "na_allowed": True,
        "tip": "For TTM: TMA operation requires specific STMS-level competency. Vehicle fleet management with driver authorisation records is expected.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Covers: H&S training/competency assessment for plant operators; how organisation tracks where plant/equipment operates and controls in place; only trained/competent/authorised people operate plant."},
            {"score": 4, "description": "Innovative controls to reduce risk to people from plant and equipment."},
        ],
        "evidence": [
            {
                "text": "Training records showing authorisation/competency for each type of plant operated (REG002 / REG003)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Process for ensuring only authorised persons operate specific plant (e.g. TMA, vehicles)",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Plant location tracking / deployment records",
                "age_label": "< 3 months old",
                "age_class": "age-1y",
                "required": False,
            },
        ],
    },
    "MB46": {
        "title": "Management of Hazardous Substances",
        "guidance": "The organisation documents the process for how it manages storage, transportation, and use of hazardous substances. NA Possible if only general household quantities.",
        "question": "Do you have a procedure or documented process for the storage, transportation, and use of hazardous substances?",
        "na_allowed": True,
        "tip": "For TTM: diesel, petrol, hydraulic fluid, oil, paints, and cleaning chemicals are typical hazardous substances. Note if they are only general household quantities.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Procedure covering: identification, inventory maintenance, SDS management, storage, transportation (if applicable), training for workers."},
            {"score": 4, "description": "Inventory includes incompatible substances, locations, waste. Correct labelling, signage, SDS accessibility for all including FENZ. Emergency response plan tested annually."},
        ],
        "evidence": [
            {
                "text": "Hazardous substances management procedure",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Hazardous substances inventory (REG007 or similar)",
                "age_label": "< 12 months old",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB47": {
        "title": "Hazardous Substances Inventory",
        "guidance": "The organisation documents and maintains an accurate hazardous substances inventory. NA Possible if only general household quantities.",
        "question": "Do you maintain a hazardous substances inventory?",
        "na_allowed": True,
        "tip": "Inventory must be dated and reviewed at least annually. SDS for each substance must be accessible.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Inventory covering: product/chemical name, maximum quantity likely stored, location, specific storage/segregation requirements."},
            {"score": 4, "description": "Inventory also covers: reviewed/dated, incompatible substances, SDS location, waste details."},
        ],
        "evidence": [
            {
                "text": "Current hazardous substances inventory listing: product name, max quantity, location, storage requirements",
                "age_label": "< 12 months old (reviewed)",
                "age_class": "age-1y",
                "required": True,
            },
        ],
    },
    "MB48": {
        "title": "Safety Data Sheets and Labelling",
        "guidance": "The organisation shows how current safety data sheets are obtained and communicated to workers, and all hazardous substances are appropriately labelled. NA Possible.",
        "question": "Describe how you get safety data sheets (SDS) for hazardous substances and communicate them to workers; and how substances are labelled.",
        "na_allowed": True,
        "tip": "SDS must not be older than 5 years. They must be sourced from the manufacturer/supplier — printouts from MSDS databases are acceptable.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes how SDS are sourced, where located, communicated to workers; three recent SDS (<5 years old) for three substances from inventory; description of labelling approach."},
            {"score": 4, "description": "SDS accessible to FENZ; meet Hazardous Substances (SDS) Notice 2017; supplied by manufacturer/supplier/importer."},
        ],
        "evidence": [
            {
                "text": "Three SDS for substances on inventory (must be dated within last 5 years)",
                "age_label": "< 5 years old (manufacturer date)",
                "age_class": "age-5y",
                "required": True,
            },
            {
                "text": "Description of where SDS are kept and how workers access them",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
            {
                "text": "Photo or description showing hazardous substances are correctly labelled",
                "age_label": "Current",
                "age_class": "age-na",
                "required": False,
            },
        ],
    },
    "MB49": {
        "title": "Hazardous Substance Training",
        "guidance": "The organisation provides evidence of required training for workers in use of hazardous substances. NA Possible.",
        "question": "Have workers been trained in the safe use and handling of hazardous substances they use or are exposed to?",
        "na_allowed": True,
        "tip": "NA applicable if only very minor household-equivalent substances. For fuels and lubricants in TTM: basic training records are expected.",
        "scoring": [
            {"score": 0, "description": "No evidence provided."},
            {"score": 1, "description": "Basic response with significant gaps."},
            {"score": 2, "description": "Addressed but gaps."},
            {"score": 3, "description": "Describes: who provided training, what training covered (hazards, use, transport, storage, emergencies). Evidence training completed — training register or records for a sample of three workers."},
            {"score": 4, "description": "Training by person(s) with adequate knowledge; covers all substances, physio-chemical hazards, safe use/PPE procedures, emergency actions, worker obligations under Hazardous Substances Regs 2017."},
        ],
        "evidence": [
            {
                "text": "Training records for hazardous substance handling for a sample of three workers",
                "age_label": "< 2 years old",
                "age_class": "age-2y",
                "required": True,
            },
            {
                "text": "Description of what hazardous substance training covers",
                "age_label": "Current",
                "age_class": "age-na",
                "required": True,
            },
        ],
    },
    "MB50": {
        "title": "Prosecution or Convictions",
        "guidance": "Organisation provides details of any prosecution/conviction relating to H&S in the last 5 years.",
        "question": "Have you been convicted of a H&S offence within the last 5 years?",
        "na_allowed": False,
        "tip": "This is information-only — no score awarded. Must disclose any convictions. Court Base search may be conducted by assessors.",
        "scoring": [
            {"score": 0, "description": "N/A — Information provision only. No score given."},
        ],
        "evidence": [
            {
                "text": "If yes: details of offence, when/where it occurred, conviction date, sentence details",
                "age_label": "Last 5 years",
                "age_class": "age-5y",
                "required": False,
            },
        ],
    },
    "MB51": {
        "title": "Enforcement Action",
        "guidance": "Organisation provides details of enforcement action by any H&S regulator in the last 5 years.",
        "question": "Have you had any enforcement action taken against you by an H&S Regulator in the last 5 years?",
        "na_allowed": False,
        "tip": "Improvement and prohibition notices must be disclosed. Provide status and any corrective actions taken.",
        "scoring": [
            {"score": 0, "description": "N/A — Information provision only. No score given."},
        ],
        "evidence": [
            {
                "text": "If yes: details of enforcement action (prohibition/improvement notices, formal warnings, enforceable undertaking), current status, primary document",
                "age_label": "Last 5 years",
                "age_class": "age-5y",
                "required": False,
            },
        ],
    },
    "MB52": {
        "title": "Investigations by Regulator",
        "guidance": "Organisation provides details of any investigation by an H&S Regulator in the last 5 years.",
        "question": "Have you ever been investigated by an H&S Regulator in the last 5 years?",
        "na_allowed": False,
        "tip": "Information provision only.",
        "scoring": [
            {"score": 0, "description": "N/A — Information provision only. No score given."},
        ],
        "evidence": [
            {
                "text": "If yes: copy or summary of investigation including required actions identified by the Regulator",
                "age_label": "Last 5 years",
                "age_class": "age-5y",
                "required": False,
            },
        ],
    },
    "MB53": {
        "title": "Environmental Offences",
        "guidance": "Organisation provides details of any environmental prosecutions or convictions in the last 5 years.",
        "question": "Have you been convicted of an Environmental offence within the last 5 years?",
        "na_allowed": False,
        "tip": "Environmental offences include Resource Management Act or Environmental Protection Authority convictions.",
        "scoring": [
            {"score": 0, "description": "N/A — Information provision only. No score given."},
        ],
        "evidence": [
            {
                "text": "If yes: details of offence, conviction date, sentence",
                "age_label": "Last 5 years",
                "age_class": "age-5y",
                "required": False,
            },
        ],
    },
    "MB54": {
        "title": "Awards and Recognitions",
        "guidance": "Organisation provides details of awards and recognitions relating to H&S in the last 5 years.",
        "question": "Have you been recognised by clients or other external bodies for H&S excellence, innovation, or problem solving in the last 5 years?",
        "na_allowed": False,
        "tip": "Information provision only — positive recognition. Attach certificate if available.",
        "scoring": [
            {"score": 0, "description": "N/A — Information provision only. No score given."},
        ],
        "evidence": [
            {
                "text": "If yes: description of award/recognition and copy of evidence",
                "age_label": "Last 5 years",
                "age_class": "age-5y",
                "required": False,
            },
        ],
    },
}
